import React from "react";

export type AILabelType = "ai" | "verified" | "broker" | "rule";

interface AILabelProps extends React.HTMLAttributes<HTMLSpanElement> {
  type: AILabelType;
  /** Override default label text */
  label?: string;
  size?: "sm" | "md";
}

const LABEL_CONFIG: Record<AILabelType, { icon: string; defaultLabel: string; bg: string; text: string; border: string }> = {
  ai: {
    icon: "⚡",
    defaultLabel: "AI Insight",
    bg: "var(--ai-bg)",
    text: "var(--ai-text)",
    border: "var(--ai-border)",
  },
  verified: {
    icon: "✓",
    defaultLabel: "ข้อมูลที่ยืนยันแล้ว",
    bg: "var(--verified-bg)",
    text: "var(--verified-text)",
    border: "var(--verified-border)",
  },
  broker: {
    icon: "👤",
    defaultLabel: "การตัดสินใจของนายหน้า",
    bg: "var(--broker-bg)",
    text: "var(--broker-text)",
    border: "var(--broker-border)",
  },
  rule: {
    icon: "⚙",
    defaultLabel: "กฎระบบ",
    bg: "var(--rule-bg)",
    text: "var(--rule-text)",
    border: "var(--rule-border)",
  },
};

/**
 * AILabel — distinguishes the provenance of displayed information.
 * Core of the AI trust visual language:
 *   ⚡ AI Insight      — generated by ML/LLM
 *   ✓ Verified Data   — confirmed customer record
 *   👤 Broker Decision — recorded by human
 *   ⚙ Rule-based      — deterministic system rule
 */
export function AILabel({ type, label, size = "sm", style, ...rest }: AILabelProps) {
  const { icon, defaultLabel, bg, text, border } = LABEL_CONFIG[type];
  const displayLabel = label ?? defaultLabel;
  const fontSize = size === "sm" ? "var(--text-xs)" : "var(--text-sm)";

  return (
    <span
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: "4px",
        padding: size === "sm" ? "2px 7px" : "3px 9px",
        backgroundColor: bg,
        border: `1px solid ${border}`,
        borderRadius: "var(--radius-full)",
        fontSize,
        fontWeight: 700,
        color: text,
        whiteSpace: "nowrap",
        letterSpacing: "0.02em",
        ...style,
      }}
      {...rest}
    >
      <span aria-hidden="true">{icon}</span>
      <span>{displayLabel}</span>
    </span>
  );
}
