// Rich synthetic demo data for Offline / Vercel Preview Mode (Strict TypeScript Typed)
import type {
  User,
  DashboardSummary,
  CustomerListItem,
  CustomerDetail,
  CustomerFullProfile,
  AnalyzeCustomerResponse,
  LLMInsightResponse,
  CustomerNeedAnalysisResponse,
  CustomerRecommendationsResponse,
  ConversationAssistantResponse,
  FollowUp,
  FollowUpSummary,
  ProductMatchOut,
  NeedCategoryScore,
  SHAPFactor,
} from "@/types";

export const MOCK_USER: User = {
  id: "u-broker-1",
  email: "broker@demo.local",
  full_name: "สมชาย มุ่งมั่น (Krungsri Certified Broker)",
  role: "broker",
  is_active: true,
};

export const MOCK_DASHBOARD_SUMMARY: DashboardSummary = {
  total_customers: 248,
  priority_breakdown: {
    high: 42,
    medium: 118,
    low: 88,
    unscored: 0,
  },
  overdue_followups_count: 3,
  open_followups_count: 14,
  kyc_breakdown: {
    verified: 215,
    pending: 28,
    rejected: 5,
  },
  total_active_policies: 382,
  total_coverage_amount: 142500000,
  total_products_available: 12,
  as_of: new Date().toISOString(),
};

export const MOCK_CUSTOMERS: CustomerListItem[] = [
  {
    id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
    external_ref: "KS-00002",
    full_name: "ณัฐชา 'เพิร์ล' ประเสริฐกิจการ",
    kyc_status: "verified",
    relationship_tier: "Silver",
    score_display: 94,
    priority_level: "high",
    score_short_reason: "Gen Z Product Designer, ประกันรถยนต์ใกล้หมด 21 วัน & มี Gap ค่าห้อง IPD ส่วนเกิน",
    why_now: "ต่ออายุประกันรถยนต์ชั้น 1 ก่อนหมดอายุเพื่อรักษาส่วนลดประวัติดี 20% & ทบทวนสิทธิประกันกลุ่มใหม่",
    recommended_action: "ส่งข้อความสรุป My Protection เสนอต่อ พ.ร.บ. + ประกันรถยนต์ และแนะแผน Top-up สุขภาพ",
    action_state: "action",
    active_policies_count: 2,
    has_overdue_followup: false,
  },
  {
    id: "d82e838c-63fb-47a3-9428-f15dc4d68883",
    external_ref: "KS-00001",
    full_name: "ณัฐพร วาริน",
    kyc_status: "verified",
    relationship_tier: "Platinum",
    score_display: 88,
    priority_level: "high",
    score_short_reason: "ประกันสุขภาพหลักใกล้ครบกำหนดต่ออายุใน 14 วัน",
    why_now: "ประกันสุขภาพหลักใกล้ครบกำหนดต่ออายุใน 14 วัน",
    recommended_action: "ประสานงานต่ออายุประกันสุขภาพพร้อมเสริมความคุ้มครองโรคร้ายแรง",
    action_state: "action",
    active_policies_count: 3,
    has_overdue_followup: false,
  },
  {
    id: "c0a451ce-a2b5-406e-9358-4a2af87721ca",
    external_ref: "KS-00004",
    full_name: "วิภา ชัยโย",
    kyc_status: "verified",
    relationship_tier: "Gold",
    score_display: 76,
    priority_level: "medium",
    score_short_reason: "เพิ่งได้รับอนุมัติสินเชื่อบ้าน 5.5M มีความเสี่ยงวงเงินคุ้มครองหนี้ (MRTA)",
    why_now: "เพิ่งได้รับอนุมัติสินเชื่อบ้าน 5.5M มีความเสี่ยงวงเงินคุ้มครองหนี้ (MRTA)",
    recommended_action: "ทบทวนทุนประกันชีวิตคุ้มครองวงเงินสินเชื่อบ้าน",
    action_state: "review",
    active_policies_count: 1,
    has_overdue_followup: false,
  },
  {
    id: "f535562e-8f70-4711-bbd0-7e092606cdd7",
    external_ref: "KS-00005",
    full_name: "ธนภูมิ ยิ้มแย้ม",
    kyc_status: "verified",
    relationship_tier: "Platinum",
    score_display: 65,
    priority_level: "medium",
    score_short_reason: "เงินฝาก AUM 14M ต้องการวางแผนลดหย่อนภาษีบำนาญ Smart Pension",
    why_now: "เงินฝาก AUM 14M ต้องการวางแผนลดหย่อนภาษีบำนาญ Smart Pension",
    recommended_action: "นัดหมายปรึกษาการออมแบบบำนาญลดหย่อนภาษีปลายปี",
    action_state: "review",
    active_policies_count: 4,
    has_overdue_followup: false,
  },
  {
    id: "50193b89-5ff9-48f1-8a52-699716fce8f5",
    external_ref: "KS-00003",
    full_name: "ปิยะ โชคดี",
    kyc_status: "verified",
    relationship_tier: "Standard",
    score_display: 28,
    priority_level: "low",
    score_short_reason: "ความคุ้มครองครบถ้วนทุกหมวดหมู่ ไม่มีความจำเป็นเร่งด่วน",
    why_now: "ความคุ้มครองครบถ้วนทุกหมวดหมู่ ไม่มีความจำเป็นเร่งด่วน",
    recommended_action: "ส่งการ์ดอวยพรวันเกิดและคงการติดต่อสัมพันธ์ระยะยาว",
    action_state: "no_action",
    active_policies_count: 2,
    has_overdue_followup: false,
  },
];

export const MOCK_FOLLOWUPS: FollowUp[] = [
  {
    id: "fu-001",
    customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
    broker_id: "u-broker-1",
    status: "open",
    renewal_date: new Date(Date.now() + 86400000 * 21).toISOString(),
    last_contact_date: "2026-09-08T10:00:00Z",
    payment_status: "pending",
    follow_up_window: "21 วัน",
    engagement_status: "ติดต่อผ่าน LINE & My Protection",
    notes: "นัดหมายคุยเรื่องต่อประกันรถยนต์และสรุปข้อดีความคุ้มครองค่าห้อง IPD",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "fu-002",
    customer_id: "d82e838c-63fb-47a3-9428-f15dc4d68883",
    broker_id: "u-broker-1",
    status: "open",
    renewal_date: new Date(Date.now() + 86400000 * 14).toISOString(),
    last_contact_date: "2026-09-05T14:30:00Z",
    payment_status: "pending",
    follow_up_window: "14 วัน",
    engagement_status: "โทรติดต่อทางโทรศัพท์",
    notes: "ส่งใบแจ้งเตือนต่ออายุกรมธรรม์สุขภาพล่วงหน้า 14 วัน",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

const MOCK_SHAP_FACTORS: SHAPFactor[] = [
  {
    feature: "days_to_motor_expiry",
    label: "นับถอยหลังต่อประกันรถยนต์ (21 วัน)",
    value: 21,
    shap_value: 0.45,
    importance: 0.45,
    impact: "positive",
  },
  {
    feature: "health_ipd_gap",
    label: "ช่องว่างค่าห้องผ่าตัด IPD ส่วนเกิน",
    value: 1,
    shap_value: 0.32,
    importance: 0.32,
    impact: "positive",
  },
  {
    feature: "digital_app_engagement",
    label: "การเข้าใช้งาน KMA My Protection",
    value: 9.2,
    shap_value: 0.17,
    importance: 0.17,
    impact: "positive",
  },
];

export const MOCK_PEARL_DETAIL: CustomerDetail = {
  id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
  external_ref: "KS-00002",
  first_name: "ณัฐชา",
  last_name: "ประเสริฐกิจการ",
  full_name: "ณัฐชา 'เพิร์ล' ประเสริฐกิจการ",
  assigned_broker_id: "u-broker-1",
  created_at: "2026-01-15T10:00:00Z",
  updated_at: "2026-09-11T08:00:00Z",
  profile: {
    id: "prof-002",
    customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
    age: 26,
    gender: "female",
    occupation: "Senior UX/UI Designer (Tech Agency)",
    income_range: "65,000 - 85,000 บาท/เดือน",
    kyc_status: "verified",
    kyc_channel: "NDID / Krungsri Mobile App",
    risk_tolerance: "ปานกลางค่อนข้างสูง (Growth-Oriented)",
    relationship_tier: "Silver",
    created_at: "2026-01-15T10:00:00Z",
    updated_at: "2026-09-01T08:00:00Z",
  },
  financial_profile: {
    id: "fin-002",
    customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
    total_assets: 1850000,
    total_liabilities: 420000,
    monthly_savings: 22000,
    has_active_loan: true,
    loan_details: "สินเชื่อเช่าซื้อรถยนต์ Honda City e:HEV (กรุงศรี ออโต้)",
    products_held: [
      "บัญชีออมทรัพย์ Krungsri Mee Tae Dai",
      "บัตรเครดิต Krungsri NOW (ช้อปออนไลน์ Cashback 5%)",
      "สินเชื่อรถยนต์ Krungsri Auto",
    ],
    transaction_frequency_90d: 48,
    last_financial_activity: "2026-09-10T11:20:00Z",
  },
  insurance_policies: [
    {
      id: "pol-001",
      customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
      policy_number: "KS-MTR-2025-0891",
      policy_type: "motor_type1",
      coverage_amount: 650000,
      premium_amount: 18500,
      start_date: "2025-10-02T00:00:00Z",
      renewal_date: new Date(Date.now() + 86400000 * 21).toISOString(),
      status: "active",
      payment_status: "paid",
      remarks: "ต่ออายุความคุ้มครองปีที่ 2 - รักษาส่วนลดประวัติดี 20%",
    },
    {
      id: "pol-002",
      customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
      policy_number: "KS-PA-2024-5120",
      policy_type: "personal_accident",
      coverage_amount: 1000000,
      premium_amount: 3200,
      start_date: "2026-02-01T00:00:00Z",
      renewal_date: "2027-02-01T00:00:00Z",
      status: "active",
      payment_status: "paid",
      remarks: "แผนคุ้มครองอุบัติเหตุ 24 ชม. ทั่วโลก",
    },
  ],
  latest_score: {
    id: "score-002",
    score: 94,
    score_display: 94,
    raw_probability: 0.942,
    calibrated_probability: 0.94,
    priority: "high",
    priority_level: "high",
    calibration_method: "isotonic",
    feature_importance: MOCK_SHAP_FACTORS,
    scored_at: "2026-09-11T08:00:00Z",
    model_version: "lgbm-priority-v2.1",
  },
  needs: [
    {
      id: "need-01",
      need_type: "motor_renewal",
      severity: "high",
      description: "กรมธรรม์รถยนต์ Honda City ใกล้ครบกำหนด 21 วัน รักษาส่วนลดประวัติดี 20%",
      identified_at: "2026-09-11T08:00:00Z",
    },
    {
      id: "need-02",
      need_type: "health_ipd_gap",
      severity: "medium",
      description: "ประกันกลุ่มบริษัทไม่ครอบคลุมค่าห้องส่วนเกินโรงพยาบาลเอกชน (ส่วนต่าง 3,000-5,000 บ.)",
      identified_at: "2026-09-11T08:00:00Z",
    },
  ],
  follow_ups: [
    {
      id: "fu-001",
      scheduled_date: new Date(Date.now() + 86400000 * 2).toISOString(),
      last_contact_date: "2026-09-08T10:00:00Z",
      follow_up_window: "21 วัน",
      status: "open",
      priority: "high",
      payment_status: "pending",
      notes: "นัดหมายคุยเรื่องต่อประกันรถยนต์และสรุปข้อดีความคุ้มครองค่าห้อง IPD",
    },
  ],
};

export const MOCK_PEARL_FULL_PROFILE: CustomerFullProfile = {
  customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
  external_ref: "KS-00002",
  full_name: "ณัฐชา 'เพิร์ล' ประเสริฐกิจการ",
  profile: MOCK_PEARL_DETAIL.profile,
  financial_profile: MOCK_PEARL_DETAIL.financial_profile,
  active_policies: MOCK_PEARL_DETAIL.insurance_policies,
  total_coverage: 1650000,
};

const MOCK_RECOMMENDED_PRODUCTS: ProductMatchOut[] = [
  {
    recommendation_id: "rec-001",
    product_id: "prod-motor-01",
    product_code: "KS-MTR-1",
    product_name: "Krungsri Motor Type 1 + พ.ร.บ. (Renewal Privilege)",
    category: "motor",
    match_score: 96,
    eligibility_status: "eligible",
    reasons: [
      "ต่ออายุความคุ้มครองรถยนต์ต่อเนื่อง รักษาส่วนลดประวัติดี 20-30% ทันที",
      "มีบริการช่วยเหลือฉุกเฉินบนท้องถนน 24 ชม. และซ่อมห้างศูนย์ Honda",
      "ผ่อนชำระ 0% สูงสุด 6 เดือนผ่านบัตรเครดิตกรุงศรี",
    ],
    unmet_criteria: [],
    coverage_range: "ทุนประกัน 650,000 บาท",
    status: "proposed",
    priority_rank: 1,
    confidence_level: "high",
    estimated_premium_annual: 16800,
    structured_explanation: {
      need_signal: "กรมธรรม์รถยนต์จะหมดอายุใน 21 วัน",
      profile_fit: "เป็นเจ้าของรถยนต์ Honda City e:HEV ขับขี่ปลอดภัยประวัติดี",
      eligibility_result: "ผ่านเกณฑ์การต่ออายุแบบ No-Claim Bonus",
      existing_coverage_assessment: "กรมธรรม์เดิมคุ้มครองถึงสิ้นเดือนหน้า ต้องต่อทันทีเพื่อไม่ให้ขาดช่วง",
    },
  },
  {
    recommendation_id: "rec-002",
    product_id: "prod-health-topup",
    product_code: "KS-HLT-TOPUP",
    product_name: "Krungsri Health Top-up (IPD Room Copay Shield)",
    category: "health",
    match_score: 88,
    eligibility_status: "eligible",
    reasons: [
      "เสริมสิทธิประกันกลุ่มบริษัท อุดช่องว่างค่าห้องโรงพยาบาลเอกชน (ส่วนเกิน 3,000-5,000 บ./คืน)",
      "เบี้ยเริ่มต้นเบาๆ เหมาะกับคนรุ่นใหม่ Gen Z ไม่ต้องตรวจสุขภาพ",
      "ลดหย่อนภาษีเงินได้บุคคลธรรมดาสูงสุด 25,000 บาท",
    ],
    unmet_criteria: [],
    coverage_range: "ค่าห้องและค่ารักษาพยาบาลส่วนเกิน 1,500,000 บาท/ปี",
    status: "proposed",
    priority_rank: 2,
    confidence_level: "high",
    estimated_premium_annual: 12500,
    structured_explanation: {
      need_signal: "มีประกันกลุ่มของบริษัทแล้วแต่ค่าห้องไม่พอสำหรับ รพ.เอกชน",
      profile_fit: "คนรุ่นใหม่วัย 26 ปี รายได้ 65k-85k ต้องการความอุ่นใจเรื่องสุขภาพ",
      eligibility_result: "เข้าเงื่อนไขอายุและสุขภาพดี",
      existing_coverage_assessment: "เดิมมีเฉพาะ PA ไม่มีประกันสุขภาพส่วนตัว",
    },
  },
];

export const MOCK_PEARL_RECOMMENDATIONS: CustomerRecommendationsResponse = {
  customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
  external_ref: "KS-00002",
  full_name: "ณัฐชา 'เพิร์ล' ประเสริฐกิจการ",
  recommendations: MOCK_RECOMMENDED_PRODUCTS,
  generated_at: new Date().toISOString(),
  disclaimer: "คำแนะนำนี้ประมวลผลผ่าน AI เพื่อเป็นแนวทางสำหรับโบรกเกอร์ในการให้คำปรึกษาเท่านั้น",
};

export const MOCK_PEARL_INSIGHTS: LLMInsightResponse = {
  customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
  customer_summary: "คุณเพิร์ลเป็นคนรุ่นใหม่ Gen Z ที่เปิดรับเทคโนโลยี KMA สูง มีพฤติกรรมการขับรถ Honda City ประจำวัน กรมธรรม์รถยนต์จะหมดอายุในอีก 21 วัน และเพิ่งเริ่มงานใหม่ทำให้สิทธิประกันกลุ่มมี Gap ค่าห้องผ่าตัด/แอดมิทโรงพยาบาลเอกชน",
  key_observations: [
    "มีความตระหนักรู้ด้านการเงินและสิทธิประโยชน์ส่วนลดสูง",
    "ขับรถไปทำงานประจำวัน และมีประวัติการขับขี่ดี ไม่เคยเคลมชนหนัก",
    "กังวลเรื่องค่าใช้จ่ายสุขภาพกรณีต้องแอดมิทโรงพยาบาลเอกชน",
  ],
  potential_needs: [
    "ต่ออายุประกันภัยรถยนต์ชั้น 1 ก่อนหมดอายุ",
    "แผนประกันสุขภาพ Top-up อุดช่องว่างค่าห้อง",
  ],
  conversation_topics: [
    "สิทธิประโยชน์ส่วนลดประวัติดี 20% ของประกันรถยนต์",
    "การคำนวณส่วนต่างค่าห้อง รพ.เอกชน ผ่านหน้า My Protection",
  ],
  cautions: [
    "หลีกเลี่ยงการขายประกันแบบผูกมัดระยะยาวที่ไม่ยืดหยุ่น",
    "เน้นการสื่อสารที่กระชับ โปร่งใส และมีตัวเลขชัดเจน",
  ],
  provider: "Google Gemini 1.5 Flash (Enterprise Guardrails)",
  model_version: "gemini-1.5-flash-krungsri-v2",
  generated_at: new Date().toISOString(),
};

const MOCK_NEEDS_LIST: NeedCategoryScore[] = [
  {
    category: "motor",
    label_th: "ประกันภัยรถยนต์ (Motor)",
    score: 95,
    severity: "high",
    supporting_signals: ["กรมธรรม์จะหมดอายุใน 21 วัน", "มีสิทธิรับส่วนลดประวัติดี 20%"],
    explanation: "ความเร่งด่วนสูงสุดเพื่อป้องกันการขาดช่วงความคุ้มครอง",
  },
  {
    category: "health",
    label_th: "ประกันสุขภาพและค่ารักษา (Health)",
    score: 82,
    severity: "medium",
    supporting_signals: ["มี Gap ค่าห้อง รพ.เอกชน", "ไม่มีประกันสุขภาพส่วนตัว"],
    explanation: "ควรทบทวนแผน Top-up เสริมประกันกลุ่มบริษัท",
  },
];

export const MOCK_PEARL_NEEDS: CustomerNeedAnalysisResponse = {
  customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
  external_ref: "KS-00002",
  full_name: "ณัฐชา 'เพิร์ล' ประเสริฐกิจการ",
  overall_need_summary: "พบความต้องการเร่งด่วน 2 ด้าน: ต่ออายุประกันรถยนต์ชั้น 1 และทบทวนส่วนต่างค่าห้องสุขภาพ",
  needs: MOCK_NEEDS_LIST,
  evaluated_at: new Date().toISOString(),
  disclaimer: "การประเมินความต้องการวิเคราะห์จากข้อมูลกรมธรรม์และการใช้งาน KMA",
};

export const MOCK_PEARL_ANALYSIS: AnalyzeCustomerResponse = {
  customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
  external_ref: "KS-00002",
  full_name: "ณัฐชา 'เพิร์ล' ประเสริฐกิจการ",
  score: 94,
  probability: 0.94,
  raw_probability: 0.942,
  calibrated_probability: 0.94,
  priority: "high",
  priority_level: "high",
  calibration_method: "isotonic",
  factors: MOCK_SHAP_FACTORS,
  model_metadata: {
    model_name: "LightGBM Priority Ranker",
    model_version: "lgbm-priority-v2.1",
    timestamp: new Date().toISOString(),
    disclaimer: "โมเดลผ่านการตรวจสอบ Fairness และ Calibration ตามมาตรฐาน ธปท.",
  },
  features_used: {
    days_to_motor_expiry: 21,
    health_coverage_gap: 1,
    digital_engagement_score: 9.2,
  },
};
