// Rich synthetic demo data for Offline / Vercel Preview Mode (Strict TypeScript Typed)
import type {
  User,
  DashboardSummary,
  CustomerListItem,
  CustomerDetail,
  CustomerFullProfile,
  AnalyzeCustomerResponse,
  LLMInsightResponse,
  CustomerNeedAnalysisResponse,
  CustomerRecommendationsResponse,
  ConversationAssistantResponse,
  FollowUp,
  FollowUpSummary,
  ProductMatchOut,
  NeedCategoryScore,
  SHAPFactor,
  AnalyticsOverviewResponse,
  PriorityAnalyticsResponse,
  NeedAnalyticsResponse,
  RecommendationAnalyticsResponse,
  FollowUpAnalyticsResponse,
  AIUsageAnalyticsResponse,
} from "@/types";

export const MOCK_USER: User = {
  id: "u-broker-1",
  email: "broker@demo.local",
  full_name: "สมชาย มุ่งมั่น (Krungsri Certified Broker)",
  role: "broker",
  is_active: true,
};

export const MOCK_DASHBOARD_SUMMARY: DashboardSummary = {
  total_customers: 248,
  priority_breakdown: {
    high: 42,
    medium: 118,
    low: 88,
    unscored: 0,
  },
  overdue_followups_count: 3,
  open_followups_count: 14,
  kyc_breakdown: {
    verified: 215,
    pending: 28,
    rejected: 5,
  },
  total_active_policies: 382,
  total_coverage_amount: 142500000,
  total_products_available: 12,
  as_of: new Date().toISOString(),
};

export const MOCK_CUSTOMERS: CustomerListItem[] = [
  {
    id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
    external_ref: "KS-00002",
    full_name: "ณัฐชา 'เพิร์ล' ประเสริฐกิจการ",
    kyc_status: "verified",
    relationship_tier: "Silver",
    score_display: 94,
    priority_level: "high",
    score_short_reason: "Gen Z Product Designer, ประกันรถยนต์ใกล้หมด 21 วัน & มี Gap ค่าห้อง IPD ส่วนเกิน",
    why_now: "ต่ออายุประกันรถยนต์ชั้น 1 ก่อนหมดอายุเพื่อรักษาส่วนลดประวัติดี 20% & ทบทวนสิทธิประกันกลุ่มใหม่",
    recommended_action: "ส่งข้อความสรุป My Protection เสนอต่อ พ.ร.บ. + ประกันรถยนต์ และแนะแผน Top-up สุขภาพ",
    action_state: "action",
    active_policies_count: 2,
    has_overdue_followup: false,
  },
  {
    id: "d82e838c-63fb-47a3-9428-f15dc4d68883",
    external_ref: "KS-00001",
    full_name: "ณัฐพร วาริน",
    kyc_status: "verified",
    relationship_tier: "Platinum",
    score_display: 92,
    priority_level: "high",
    score_short_reason: "ประกันสุขภาพหลักใกล้ครบกำหนดต่ออายุใน 14 วัน (โอกาสเสนอ CI Protect)",
    why_now: "ประกันสุขภาพหลักใกล้ครบกำหนดต่ออายุใน 14 วัน (โอกาสเสนอ CI Protect)",
    recommended_action: "ประสานงานต่ออายุประกันสุขภาพพร้อมเสริมความคุ้มครองโรคร้ายแรง",
    action_state: "action",
    active_policies_count: 3,
    has_overdue_followup: false,
  },
  {
    id: "c0a451ce-a2b5-406e-9358-4a2af87721ca",
    external_ref: "KS-00004",
    full_name: "วิภา ชัยโย",
    kyc_status: "verified",
    relationship_tier: "Gold",
    score_display: 88,
    priority_level: "high",
    score_short_reason: "เพิ่งได้รับอนุมัติสินเชื่อบ้าน 5.5M ไร้ประกันคุ้มครองวงเงินหนี้ (MRTA Gap)",
    why_now: "เพิ่งได้รับอนุมัติสินเชื่อบ้าน 5.5M ไร้ประกันคุ้มครองวงเงินหนี้ (MRTA Gap)",
    recommended_action: "ทบทวนทุนประกันชีวิตคุ้มครองวงเงินสินเชื่อบ้าน Krungsri MRTA",
    action_state: "action",
    active_policies_count: 1,
    has_overdue_followup: false,
  },
  {
    id: "73684349-2be5-442a-aa25-373938e4a3f2",
    external_ref: "KS-00007",
    full_name: "อานนท์ ก้าวหน้า",
    kyc_status: "verified",
    relationship_tier: "Gold",
    score_display: 82,
    priority_level: "high",
    score_short_reason: "กรมธรรม์ Life Plus ครบกำหนดใน 20 วัน & มีสินเชื่อหมุนเวียนธุรกิจ SME 2.5M",
    why_now: "กรมธรรม์ Life Plus ครบกำหนดใน 20 วัน & มีสินเชื่อหมุนเวียนธุรกิจ SME 2.5M",
    recommended_action: "แจ้งเตือนต่ออายุและเสริมความคุ้มครอง Keyman Protection / CI Protect",
    action_state: "action",
    active_policies_count: 1,
    has_overdue_followup: false,
  },
  {
    id: "f535562e-8f70-4711-bbd0-7e092606cdd7",
    external_ref: "KS-00005",
    full_name: "ธนภูมิ ยิ้มแย้ม",
    kyc_status: "verified",
    relationship_tier: "Platinum",
    score_display: 65,
    priority_level: "medium",
    score_short_reason: "เงินฝาก AUM 14.2M วางแผนบำนาญก่อนเกษียณ Smart Pension 85/60",
    why_now: "เงินฝาก AUM 14.2M วางแผนบำนาญก่อนเกษียณ Smart Pension 85/60",
    recommended_action: "นัดหมายปรึกษาการออมแบบบำนาญลดหย่อนภาษีปลายปีวงเงิน 200,000 บาท",
    action_state: "review",
    active_policies_count: 4,
    has_overdue_followup: false,
  },
  {
    id: "0d76a238-a48a-40bd-8ebb-0051fea69f3f",
    external_ref: "KS-00008",
    full_name: "ณัฐพร ทวีผล",
    kyc_status: "verified",
    relationship_tier: "Standard",
    score_display: 50,
    priority_level: "medium",
    score_short_reason: "ลูกค้าสูงอายุ 68 ปี ผ่านการตรวจ Hard-Gating แนะนำวางแผนมรดกครอบครัว",
    why_now: "ลูกค้าสูงอายุ 68 ปี ผ่านการตรวจ Hard-Gating แนะนำวางแผนมรดกครอบครัว",
    recommended_action: "ทบทวนผู้รับประโยชน์และแผนการส่งต่อมรดก Krungsri Life Plus",
    action_state: "review",
    active_policies_count: 1,
    has_overdue_followup: false,
  },
  {
    id: "0dd17657-a534-4f57-836c-26d73cc0c2e5",
    external_ref: "KS-00006",
    full_name: "วิภา รุ่งเรือง",
    kyc_status: "pending",
    relationship_tier: "Standard",
    score_display: 48,
    priority_level: "medium",
    score_short_reason: "สถาปนิกอิสระ สถานะ KYC รอยืนยันตัวตน มีศักยภาพออมเงินสะสมทรัพย์ 10/5",
    why_now: "สถานะ KYC รอยืนยันตัวตน ต้องเร่งอัปเดตเพื่อเปิดรับสิทธิประโยชน์",
    recommended_action: "แนะนำขั้นตอน Dip-Chip ยืนยันตัวตนผ่าน KMA/สาขา และเสนอแบบประกันสะสมทรัพย์ 10/5",
    action_state: "review",
    active_policies_count: 0,
    has_overdue_followup: false,
  },
  {
    id: "50193b89-5ff9-48f1-8a52-699716fce8f5",
    external_ref: "KS-00003",
    full_name: "ปิยะ โชคดี",
    kyc_status: "verified",
    relationship_tier: "Standard",
    score_display: 22,
    priority_level: "low",
    score_short_reason: "เพิ่งบริการเสร็จสิ้นเมื่อ 7 วันก่อน กรมธรรม์เหลือ 280 วัน ความคุ้มครองครบถ้วน",
    why_now: "เพิ่งบริการเสร็จสิ้นเมื่อ 7 วันก่อน กรมธรรม์เหลือ 280 วัน ความคุ้มครองครบถ้วน",
    recommended_action: "คงการติดต่อสัมพันธ์ระยะยาวผ่านระบบดิจิทัล ไม่จำเป็นต้องโทรเร่งรัด",
    action_state: "no_action",
    active_policies_count: 2,
    has_overdue_followup: false,
  },
];

export const MOCK_FOLLOWUPS: FollowUp[] = [
  {
    id: "fu-001",
    customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
    broker_id: "u-broker-1",
    status: "open",
    renewal_date: new Date(Date.now() + 86400000 * 21).toISOString(),
    last_contact_date: "2026-09-08T10:00:00Z",
    payment_status: "pending",
    follow_up_window: "21 วัน",
    engagement_status: "ติดต่อผ่าน LINE & My Protection",
    notes: "นัดหมายคุยเรื่องต่อประกันรถยนต์และสรุปข้อดีความคุ้มครองค่าห้อง IPD",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "fu-002",
    customer_id: "d82e838c-63fb-47a3-9428-f15dc4d68883",
    broker_id: "u-broker-1",
    status: "open",
    renewal_date: new Date(Date.now() + 86400000 * 14).toISOString(),
    last_contact_date: "2026-09-05T14:30:00Z",
    payment_status: "pending",
    follow_up_window: "14 วัน",
    engagement_status: "โทรติดต่อทางโทรศัพท์",
    notes: "ส่งใบแจ้งเตือนต่ออายุกรมธรรม์สุขภาพล่วงหน้า 14 วัน",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

const MOCK_SHAP_FACTORS: SHAPFactor[] = [
  {
    feature: "days_to_motor_expiry",
    label: "นับถอยหลังต่อประกันรถยนต์ (21 วัน)",
    value: 21,
    shap_value: 0.45,
    importance: 0.45,
    impact: "positive",
  },
  {
    feature: "health_ipd_gap",
    label: "ช่องว่างค่าห้องผ่าตัด IPD ส่วนเกิน",
    value: 1,
    shap_value: 0.32,
    importance: 0.32,
    impact: "positive",
  },
  {
    feature: "digital_app_engagement",
    label: "การเข้าใช้งาน KMA My Protection",
    value: 9.2,
    shap_value: 0.17,
    importance: 0.17,
    impact: "positive",
  },
];

export const MOCK_PEARL_DETAIL: CustomerDetail = {
  id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
  external_ref: "KS-00002",
  first_name: "ณัฐชา",
  last_name: "ประเสริฐกิจการ",
  full_name: "ณัฐชา 'เพิร์ล' ประเสริฐกิจการ",
  assigned_broker_id: "u-broker-1",
  created_at: "2026-01-15T10:00:00Z",
  updated_at: "2026-09-11T08:00:00Z",
  profile: {
    id: "prof-002",
    customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
    age: 26,
    gender: "female",
    occupation: "Senior UX/UI Designer (Tech Agency)",
    income_range: "65,000 - 85,000 บาท/เดือน",
    kyc_status: "verified",
    kyc_channel: "NDID / Krungsri Mobile App",
    risk_tolerance: "ปานกลางค่อนข้างสูง (Growth-Oriented)",
    relationship_tier: "Silver",
    created_at: "2026-01-15T10:00:00Z",
    updated_at: "2026-09-01T08:00:00Z",
  },
  financial_profile: {
    id: "fin-002",
    customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
    total_assets: 1850000,
    total_liabilities: 420000,
    monthly_savings: 22000,
    has_active_loan: true,
    loan_details: "สินเชื่อเช่าซื้อรถยนต์ Honda City e:HEV (กรุงศรี ออโต้)",
    products_held: [
      "บัญชีเงินเดือน Krungsri Payroll (เลขที่ 047-1-89234-5)",
      "บัญชีออมทรัพย์มีแต่ได้ Krungsri Mee Tae Dai (ดอกเบี้ยสูง)",
      "บัตรเครดิต Krungsri NOW (Cashback 5% ช้อปออนไลน์)",
      "สินเชื่อเช่าซื้อรถยนต์ Krungsri Auto (ผ่อนชำระตรงเวลา)",
      "กองทุนรวม Krungsri Global Core Equity (KF-GLOBE ผ่าน Dime!)",
    ],
    transaction_frequency_90d: 48,
    last_financial_activity: "2026-09-10T11:20:00Z",
  },
  insurance_policies: [
    {
      id: "pol-001",
      customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
      policy_number: "KM-2025-089124",
      policy_type: "motor_type1",
      coverage_amount: 650000,
      premium_amount: 18500,
      start_date: "2025-10-02T00:00:00Z",
      renewal_date: new Date(Date.now() + 86400000 * 21).toISOString(),
      status: "active",
      payment_status: "paid",
      remarks: "ต่ออายุความคุ้มครองปีที่ 2 - รักษาส่วนลดประวัติดี (NCB 20%) ซ่อมห้างศูนย์ Honda",
    },
    {
      id: "pol-002",
      customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
      policy_number: "KPA-2024-512089",
      policy_type: "personal_accident",
      coverage_amount: 1000000,
      premium_amount: 3200,
      start_date: "2026-02-01T00:00:00Z",
      renewal_date: "2027-02-01T00:00:00Z",
      status: "active",
      payment_status: "paid",
      remarks: "แผนคุ้มครองอุบัติเหตุส่วนบุคคล Krungsri PA Hospital Care 24 ชม.",
    },
  ],
  latest_score: {
    id: "score-002",
    score: 94,
    score_display: 94,
    raw_probability: 0.942,
    calibrated_probability: 0.94,
    priority: "high",
    priority_level: "high",
    calibration_method: "isotonic",
    feature_importance: MOCK_SHAP_FACTORS,
    scored_at: "2026-09-11T08:00:00Z",
    model_version: "lgbm-priority-v2.1",
  },
  needs: [
    {
      id: "need-01",
      need_type: "motor_renewal",
      severity: "high",
      description: "กรมธรรม์รถยนต์ Honda City ใกล้ครบกำหนด 21 วัน รักษาส่วนลดประวัติดี 20%",
      identified_at: "2026-09-11T08:00:00Z",
    },
    {
      id: "need-02",
      need_type: "health_ipd_gap",
      severity: "medium",
      description: "ประกันกลุ่มบริษัทไม่ครอบคลุมค่าห้องส่วนเกินโรงพยาบาลเอกชน (ส่วนต่าง 3,000-5,000 บ.)",
      identified_at: "2026-09-11T08:00:00Z",
    },
  ],
  follow_ups: [
    {
      id: "fu-001",
      scheduled_date: new Date(Date.now() + 86400000 * 2).toISOString(),
      last_contact_date: "2026-09-08T10:00:00Z",
      follow_up_window: "21 วัน",
      status: "open",
      priority: "high",
      payment_status: "pending",
      notes: "นัดหมายคุยเรื่องต่อประกันรถยนต์และสรุปข้อดีความคุ้มครองค่าห้อง IPD",
    },
  ],
};

export const MOCK_PEARL_FULL_PROFILE: CustomerFullProfile = {
  customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
  external_ref: "KS-00002",
  full_name: "ณัฐชา 'เพิร์ล' ประเสริฐกิจการ",
  profile: MOCK_PEARL_DETAIL.profile,
  financial_profile: MOCK_PEARL_DETAIL.financial_profile,
  active_policies: MOCK_PEARL_DETAIL.insurance_policies,
  total_coverage: 1650000,
};

const MOCK_RECOMMENDED_PRODUCTS: ProductMatchOut[] = [
  {
    recommendation_id: "rec-001",
    product_id: "prod-motor-01",
    product_code: "KS-MTR-1",
    product_name: "Krungsri Motor Type 1 + พ.ร.บ. (Renewal Privilege)",
    category: "motor",
    match_score: 96,
    eligibility_status: "eligible",
    reasons: [
      "ต่ออายุความคุ้มครองรถยนต์ต่อเนื่อง รักษาส่วนลดประวัติดี 20-30% ทันที",
      "มีบริการช่วยเหลือฉุกเฉินบนท้องถนน 24 ชม. และซ่อมห้างศูนย์ Honda",
      "ผ่อนชำระ 0% สูงสุด 6 เดือนผ่านบัตรเครดิตกรุงศรี",
    ],
    unmet_criteria: [],
    coverage_range: "ทุนประกัน 650,000 บาท",
    status: "proposed",
    priority_rank: 1,
    confidence_level: "high",
    estimated_premium_annual: 16800,
    structured_explanation: {
      need_signal: "กรมธรรม์รถยนต์จะหมดอายุใน 21 วัน",
      profile_fit: "เป็นเจ้าของรถยนต์ Honda City e:HEV ขับขี่ปลอดภัยประวัติดี",
      eligibility_result: "ผ่านเกณฑ์การต่ออายุแบบ No-Claim Bonus",
      existing_coverage_assessment: "กรมธรรม์เดิมคุ้มครองถึงสิ้นเดือนหน้า ต้องต่อทันทีเพื่อไม่ให้ขาดช่วง",
    },
  },
  {
    recommendation_id: "rec-002",
    product_id: "prod-health-topup",
    product_code: "KS-HLT-TOPUP",
    product_name: "Krungsri Health Top-up (IPD Room Copay Shield)",
    category: "health",
    match_score: 88,
    eligibility_status: "eligible",
    reasons: [
      "เสริมสิทธิประกันกลุ่มบริษัท อุดช่องว่างค่าห้องโรงพยาบาลเอกชน (ส่วนเกิน 3,000-5,000 บ./คืน)",
      "เบี้ยเริ่มต้นเบาๆ เหมาะกับคนรุ่นใหม่ Gen Z ไม่ต้องตรวจสุขภาพ",
      "ลดหย่อนภาษีเงินได้บุคคลธรรมดาสูงสุด 25,000 บาท",
    ],
    unmet_criteria: [],
    coverage_range: "ค่าห้องและค่ารักษาพยาบาลส่วนเกิน 1,500,000 บาท/ปี",
    status: "proposed",
    priority_rank: 2,
    confidence_level: "high",
    estimated_premium_annual: 12500,
    structured_explanation: {
      need_signal: "มีประกันกลุ่มของบริษัทแล้วแต่ค่าห้องไม่พอสำหรับ รพ.เอกชน",
      profile_fit: "คนรุ่นใหม่วัย 26 ปี รายได้ 65k-85k ต้องการความอุ่นใจเรื่องสุขภาพ",
      eligibility_result: "เข้าเงื่อนไขอายุและสุขภาพดี",
      existing_coverage_assessment: "เดิมมีเฉพาะ PA ไม่มีประกันสุขภาพส่วนตัว",
    },
  },
];

export const MOCK_PEARL_RECOMMENDATIONS: CustomerRecommendationsResponse = {
  customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
  external_ref: "KS-00002",
  full_name: "ณัฐชา 'เพิร์ล' ประเสริฐกิจการ",
  recommendations: MOCK_RECOMMENDED_PRODUCTS,
  generated_at: new Date().toISOString(),
  disclaimer: "คำแนะนำนี้ประมวลผลผ่าน AI เพื่อเป็นแนวทางสำหรับโบรกเกอร์ในการให้คำปรึกษาเท่านั้น",
};

export const MOCK_PEARL_INSIGHTS: LLMInsightResponse = {
  customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
  customer_summary: "คุณเพิร์ลเป็นคนรุ่นใหม่ Gen Z ที่เปิดรับเทคโนโลยี KMA สูง มีพฤติกรรมการขับรถ Honda City ประจำวัน กรมธรรม์รถยนต์จะหมดอายุในอีก 21 วัน และเพิ่งเริ่มงานใหม่ทำให้สิทธิประกันกลุ่มมี Gap ค่าห้องผ่าตัด/แอดมิทโรงพยาบาลเอกชน",
  key_observations: [
    "มีความตระหนักรู้ด้านการเงินและสิทธิประโยชน์ส่วนลดสูง",
    "ขับรถไปทำงานประจำวัน และมีประวัติการขับขี่ดี ไม่เคยเคลมชนหนัก",
    "กังวลเรื่องค่าใช้จ่ายสุขภาพกรณีต้องแอดมิทโรงพยาบาลเอกชน",
  ],
  potential_needs: [
    "ต่ออายุประกันภัยรถยนต์ชั้น 1 ก่อนหมดอายุ",
    "แผนประกันสุขภาพ Top-up อุดช่องว่างค่าห้อง",
  ],
  conversation_topics: [
    "สิทธิประโยชน์ส่วนลดประวัติดี 20% ของประกันรถยนต์",
    "การคำนวณส่วนต่างค่าห้อง รพ.เอกชน ผ่านหน้า My Protection",
  ],
  cautions: [
    "หลีกเลี่ยงการขายประกันแบบผูกมัดระยะยาวที่ไม่ยืดหยุ่น",
    "เน้นการสื่อสารที่กระชับ โปร่งใส และมีตัวเลขชัดเจน",
  ],
  provider: "Google Gemini 1.5 Flash (Enterprise Guardrails)",
  model_version: "gemini-1.5-flash-krungsri-v2",
  generated_at: new Date().toISOString(),
};

const MOCK_NEEDS_LIST: NeedCategoryScore[] = [
  {
    category: "motor",
    label_th: "ประกันภัยรถยนต์ (Motor)",
    score: 95,
    severity: "high",
    supporting_signals: ["กรมธรรม์จะหมดอายุใน 21 วัน", "มีสิทธิรับส่วนลดประวัติดี 20%"],
    explanation: "ความเร่งด่วนสูงสุดเพื่อป้องกันการขาดช่วงความคุ้มครอง",
  },
  {
    category: "health",
    label_th: "ประกันสุขภาพและค่ารักษา (Health)",
    score: 82,
    severity: "medium",
    supporting_signals: ["มี Gap ค่าห้อง รพ.เอกชน", "ไม่มีประกันสุขภาพส่วนตัว"],
    explanation: "ควรทบทวนแผน Top-up เสริมประกันกลุ่มบริษัท",
  },
];

export const MOCK_PEARL_NEEDS: CustomerNeedAnalysisResponse = {
  customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
  external_ref: "KS-00002",
  full_name: "ณัฐชา 'เพิร์ล' ประเสริฐกิจการ",
  overall_need_summary: "พบความต้องการเร่งด่วน 2 ด้าน: ต่ออายุประกันรถยนต์ชั้น 1 และทบทวนส่วนต่างค่าห้องสุขภาพ",
  needs: MOCK_NEEDS_LIST,
  evaluated_at: new Date().toISOString(),
  disclaimer: "การประเมินความต้องการวิเคราะห์จากข้อมูลกรมธรรม์และการใช้งาน KMA",
};

export const MOCK_PEARL_ANALYSIS: AnalyzeCustomerResponse = {
  customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
  external_ref: "KS-00002",
  full_name: "ณัฐชา 'เพิร์ล' ประเสริฐกิจการ",
  score: 94,
  probability: 0.94,
  raw_probability: 0.942,
  calibrated_probability: 0.94,
  priority: "high",
  priority_level: "high",
  calibration_method: "isotonic",
  factors: MOCK_SHAP_FACTORS,
  model_metadata: {
    model_name: "LightGBM Priority Ranker",
    model_version: "lgbm-priority-v2.1",
    timestamp: new Date().toISOString(),
    disclaimer: "โมเดลผ่านการตรวจสอบ Fairness และ Calibration ตามมาตรฐาน ธปท.",
  },
  features_used: {
    days_to_motor_expiry: 21,
    health_coverage_gap: 1,
    digital_engagement_score: 9.2,
  },
};

// ── Visit Planner Mock Data ─────────────────────────────────────────

export const MOCK_VISIT_PLANNER_CONFIG = {
  office_start_time: "08:30",
  office_end_time: "17:30",
  max_daily_travel_time_minutes: 150,
  max_daily_distance_km: 60.0,
  default_meeting_duration_minutes: 45,
  start_location: {
    name: "ธนาคารกรุงศรีอยุธยา สำนักพระรามที่ 3 (สำนักงานใหญ่)",
    address: "1222 ถนนพระรามที่ 3 แขวงบางโพงพาง เขตยานนาวา กรุงเทพฯ 10120",
    latitude: 13.6827,
    longitude: 100.5478,
  },
  end_location: {
    name: "ธนาคารกรุงศรีอยุธยา สำนักพระรามที่ 3 (สำนักงานใหญ่)",
    address: "1222 ถนนพระรามที่ 3 แขวงบางโพงพาง เขตยานนาวา กรุงเทพฯ 10120",
    latitude: 13.6827,
    longitude: 100.5478,
  },
  available_offices: [
    {
      id: "krungsri-rama3",
      name: "ธนาคารกรุงศรีอยุธยา สำนักพระรามที่ 3 (สำนักงานใหญ่)",
      address: "1222 ถนนพระรามที่ 3 แขวงบางโพงพาง เขตยานนาวา กรุงเทพฯ 10120",
      latitude: 13.6827,
      longitude: 100.5478,
      is_headquarters: true,
    },
    {
      id: "krungsri-ploenchit",
      name: "ธนาคารกรุงศรีอยุธยา อาคารกรุงศรี เพลินจิต ทาวเวอร์",
      address: "550 ถนนเพลินจิต แขวงลุมพินี เขตปทุมวัน กรุงเทพมหานคร 10330",
      latitude: 13.7428,
      longitude: 100.5471,
      is_headquarters: false,
    },
    {
      id: "krungsri-sathorn",
      name: "ธนาคารกรุงศรีอยุธยา สาขาสาทร (อาคารสาทรสแควร์)",
      address: "98 ถนนสาทรเหนือ แขวงสีลม เขตบางรัก กรุงเทพมหานคร 10500",
      latitude: 13.7219,
      longitude: 100.5303,
      is_headquarters: false,
    },
  ],
};

export const MOCK_VISIT_PLANNER_CANDIDATES = [
  {
    customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
    external_ref: "KS-00002",
    customer_name: "ณัฐชา 'เพิร์ล' ประเสริฐกิจการ",
    display_name: "ณัฐชา 'เพิร์ล' ประเสริฐกิจการ (KS-00002)",
    latitude: 13.7225,
    longitude: 100.5284,
    location_available: true,
    address: "88 อาคารสาทรสแควร์ ถนนสาทรเหนือ แขวงสีลม",
    district: "บางรัก",
    province: "กรุงเทพมหานคร",
    postal_code: "10500",
    priority_score: 94,
    priority_level: "high" as const,
    why_now: "ต่ออายุประกันรถยนต์ชั้น 1 ก่อนหมดอายุใน 21 วัน เพื่อรักษาส่วนลดประวัติดี 20%",
    recommended_next_action: "นำเสนอสรุปความคุ้มครอง My Protection และแนะนำต่อ พ.ร.บ. + ประกันรถยนต์",
    action_state: "action",
    protection_gap: "ขาดค่าห้อง IPD รพ.เอกชนส่วนเกิน",
    latest_customer_update: "2026-09-12T07:00:00Z",
    follow_up_status: "open",
    kyc_status: "verified",
    relationship_tier: "Silver",
    active_policies_count: 2,
    routable: true,
    unroutable_reason: null,
  },
  {
    customer_id: "d82e838c-63fb-47a3-9428-f15dc4d68883",
    external_ref: "KS-00001",
    customer_name: "ณัฐพร วาริน",
    display_name: "ณัฐพร วาริน (KS-00001)",
    latitude: 13.7314,
    longitude: 100.5815,
    location_available: true,
    address: "99/1 ซอยทองหล่อ 10 แขวงคลองตันเหนือ",
    district: "วัฒนา",
    province: "กรุงเทพมหานคร",
    postal_code: "10110",
    priority_score: 92,
    priority_level: "high" as const,
    why_now: "กรมธรรม์สุขภาพ Krungsri Health Max 5M มีกำหนดต่ออายุใน 14 วัน",
    recommended_next_action: "ประสานงานต่ออายุประกันสุขภาพพร้อมนำเสนอความคุ้มครองโรคร้ายแรง CI Protect",
    action_state: "action",
    protection_gap: "ขาดความคุ้มครองโรคร้ายแรงระยะวิกฤต (CI Gap)",
    latest_customer_update: "2026-09-11T14:30:00Z",
    follow_up_status: "open",
    kyc_status: "verified",
    relationship_tier: "Platinum",
    active_policies_count: 3,
    routable: true,
    unroutable_reason: null,
  },
  {
    customer_id: "c0a451ce-a2b5-406e-9358-4a2af87721ca",
    external_ref: "KS-00004",
    customer_name: "วิภา ชัยโย",
    display_name: "วิภา ชัยโย (KS-00004)",
    latitude: 13.7372,
    longitude: 100.5621,
    location_available: true,
    address: "253 ถนนสุขุมวิท 21 (อโศก) แขวงคลองเตยเหนือ",
    district: "วัฒนา",
    province: "กรุงเทพมหานคร",
    postal_code: "10110",
    priority_score: 88,
    priority_level: "high" as const,
    why_now: "เพิ่งได้รับอนุมัติสินเชื่อบ้าน 5.5 ล้านบาท ไร้ประกันคุ้มครองวงเงินหนี้ (MRTA)",
    recommended_next_action: "ทบทวนทุนประกันชีวิตคุ้มครองวงเงินสินเชื่อบ้าน Krungsri MRTA",
    action_state: "action",
    protection_gap: "ภาระหนี้บ้าน 5.5 ล้านบาท ไร้ประกันคุ้มครอง",
    latest_customer_update: "2026-09-10T09:15:00Z",
    follow_up_status: "open",
    kyc_status: "verified",
    relationship_tier: "Gold",
    active_policies_count: 1,
    routable: true,
    unroutable_reason: null,
  },
  {
    customer_id: "f535562e-8f70-4711-bbd0-7e092606cdd7",
    external_ref: "KS-00005",
    customer_name: "ธนภูมิ ยิ้มแย้ม",
    display_name: "ธนภูมิ ยิ้มแย้ม (KS-00005)",
    latitude: 13.7428,
    longitude: 100.5482,
    location_available: true,
    address: "55 อาคารปาร์คเวนเชอร์ เพลินจิต ถนนวิทยุ แขวงลุมพินี",
    district: "ปทุมวัน",
    province: "กรุงเทพมหานคร",
    postal_code: "10330",
    priority_score: 65,
    priority_level: "medium" as const,
    why_now: "พอร์ตเงินฝาก AUM 14.2M ต้องการวางแผนรับกระแสเงินสดหลังเกษียณ",
    recommended_next_action: "นัดหมายนำเสนอแผนประกันบำนาญ Krungsri Smart Pension 85/60",
    action_state: "review",
    protection_gap: "ยังไม่มีกระแสเงินสดประจำหลังเกษียณอายุ 60 ปี",
    latest_customer_update: "2026-09-08T11:00:00Z",
    follow_up_status: "open",
    kyc_status: "verified",
    relationship_tier: "Platinum",
    active_policies_count: 4,
    routable: true,
    unroutable_reason: null,
  },
  {
    customer_id: "0dd17657-a534-4f57-836c-26d73cc0c2e5",
    external_ref: "KS-00006",
    customer_name: "วิภา รุ่งเรือง",
    display_name: "วิภา รุ่งเรือง (KS-00006)",
    latitude: null,
    longitude: null,
    location_available: false,
    address: null,
    district: "ดอนเมือง",
    province: "กรุงเทพมหานคร",
    postal_code: "10210",
    priority_score: 48,
    priority_level: "medium" as const,
    why_now: "สถานะ KYC ค้างอยู่ในระบบ รอยืนยันตัวตนเพื่อเริ่มออมประกันสะสมทรัพย์",
    recommended_action: "โทรแนะนำขั้นตอน Dip-Chip ยืนยันตัวตน และเสนอแบบประกันสะสมทรัพย์ 10/5",
    action_state: "review",
    protection_gap: "ยังไม่มีประวัติการถือครองประกันในระบบ (New to Insurance)",
    latest_customer_update: "2026-09-09T16:20:00Z",
    follow_up_status: "open",
    kyc_status: "pending",
    relationship_tier: "Standard",
    active_policies_count: 0,
    routable: false,
    unroutable_reason: "พิกัดที่อยู่ไม่สมบูรณ์ (Missing Coordinates) — รออัปเดตข้อมูลยืนยันตัวตน KYC",
  },
];

export const MOCK_VISIT_PLANNER_ROUTE = {
  status: "feasible" as const,
  is_feasible: true,
  summary: "จัดเส้นทางเข้าพบลูกค้า 3 ราย รวมระยะทาง 21.8 กม. ใช้เวลาเดินทาง 52 นาที จัดลำดับตามลำดับความสำคัญและความคุ้มค่าในการเดินทาง (Loop Route)",
  total_customers_to_visit: 3,
  total_stops: 5,
  total_distance_km: 21.8,
  total_travel_time_minutes: 52.0,
  total_meeting_time_minutes: 135,
  total_duration_minutes: 187.0,
  start_location: {
    name: "ธนาคารกรุงศรีอยุธยา สำนักพระรามที่ 3 (สำนักงานใหญ่)",
    address: "1222 ถนนพระรามที่ 3 แขวงบางโพงพาง เขตยานนาวา กรุงเทพฯ 10120",
    latitude: 13.6827,
    longitude: 100.5478,
  },
  end_location: {
    name: "ธนาคารกรุงศรีอยุธยา สำนักพระรามที่ 3 (สำนักงานใหญ่)",
    address: "1222 ถนนพระรามที่ 3 แขวงบางโพงพาง เขตยานนาวา กรุงเทพฯ 10120",
    latitude: 13.6827,
    longitude: 100.5478,
  },
  working_window: {
    office_start_time: "08:30",
    office_end_time: "17:30",
    window_minutes: 540.0,
    used_minutes: 187.0,
    remaining_minutes: 353.0,
    utilization_pct: 34.6,
    estimated_return_time: "11:37",
  },
  limits: {
    max_travel_time_minutes: 150,
    actual_travel_time_minutes: 52.0,
    travel_time_utilization_pct: 34.7,
    max_distance_km: 60.0,
    actual_distance_km: 21.8,
    distance_utilization_pct: 36.3,
  },
  visits: [
    {
      visit_order: 1,
      customer: {
        customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
        external_ref: "KS-00002",
        customer_name: "ณัฐชา 'เพิร์ล' ประเสริฐกิจการ",
        display_name: "ณัฐชา 'เพิร์ล' ประเสริฐกิจการ (KS-00002)",
        kyc_status: "verified",
        relationship_tier: "Silver",
        active_policies_count: 2,
        protection_gap: "ขาดค่าห้อง IPD รพ.เอกชนส่วนเกิน",
        follow_up_status: "open",
      },
      priority_level: "high",
      priority_score: 94,
      why_now: "ต่ออายุประกันรถยนต์ชั้น 1 ก่อนหมดอายุใน 21 วัน เพื่อรักษาส่วนลดประวัติดี 20%",
      recommended_next_action: "นำเสนอสรุปความคุ้มครอง My Protection และแนะนำต่อ พ.ร.บ. + ประกันรถยนต์",
      action_state: "action",
      location: {
        name: "สาทรสแควร์, กรุงเทพฯ",
        address: "88 อาคารสาทรสแควร์ ถนนสาทรเหนือ แขวงสีลม",
        district: "บางรัก",
        province: "กรุงเทพมหานคร",
        postal_code: "10500",
        latitude: 13.7225,
        longitude: 100.5284,
      },
      transit_time_from_prev_minutes: 14.0,
      distance_from_prev_km: 5.6,
      explanation: "จัดเข้าพบเป็นลำดับแรก ออกจากสำนักงานใหญ่พระราม 3 มุ่งหน้าสู่ถนนสาทรเหนือ ความเร่งด่วนสูงสุด (Score 94, ประกันรถยนต์หมดอายุใน 21 วัน)",
    },
    {
      visit_order: 2,
      customer: {
        customer_id: "d82e838c-63fb-47a3-9428-f15dc4d68883",
        external_ref: "KS-00001",
        customer_name: "ณัฐพร วาริน",
        display_name: "ณัฐพร วาริน (KS-00001)",
        kyc_status: "verified",
        relationship_tier: "Platinum",
        active_policies_count: 3,
        protection_gap: "ขาดความคุ้มครองโรคร้ายแรงระยะวิกฤต (CI Gap)",
        follow_up_status: "open",
      },
      priority_level: "high",
      priority_score: 92,
      why_now: "กรมธรรม์สุขภาพ Krungsri Health Max 5M มีกำหนดต่ออายุใน 14 วัน",
      recommended_next_action: "ประสานงานต่ออายุประกันสุขภาพพร้อมนำเสนอความคุ้มครองโรคร้ายแรง CI Protect",
      action_state: "action",
      location: {
        name: "ทองหล่อ 10, กรุงเทพฯ",
        address: "99/1 ซอยทองหล่อ 10 แขวงคลองตันเหนือ",
        district: "วัฒนา",
        province: "กรุงเทพมหานคร",
        postal_code: "10110",
        latitude: 13.7314,
        longitude: 100.5815,
      },
      transit_time_from_prev_minutes: 18.0,
      distance_from_prev_km: 7.8,
      explanation: "จัดเข้าพบต่อเนื่องจากสาทรมุ่งสู่ย่านทองหล่อ เพื่อพบคุณณัฐพร (Platinum Tier · AUM 18.5M) ยืนยันการต่ออายุ Health Max ใน 14 วัน",
    },
    {
      visit_order: 3,
      customer: {
        customer_id: "c0a451ce-a2b5-406e-9358-4a2af87721ca",
        external_ref: "KS-00004",
        customer_name: "วิภา ชัยโย",
        display_name: "วิภา ชัยโย (KS-00004)",
        kyc_status: "verified",
        relationship_tier: "Gold",
        active_policies_count: 1,
        protection_gap: "ภาระหนี้บ้าน 5.5 ล้านบาท ไร้ประกันคุ้มครอง",
        follow_up_status: "open",
      },
      priority_level: "high",
      priority_score: 88,
      why_now: "เพิ่งได้รับอนุมัติสินเชื่อบ้าน 5.5 ล้านบาท ไร้ประกันคุ้มครองวงเงินหนี้ (MRTA)",
      recommended_next_action: "ทบทวนทุนประกันชีวิตคุ้มครองวงเงินสินเชื่อบ้าน Krungsri MRTA",
      action_state: "action",
      location: {
        name: "อโศก สุขุมวิท 21, กรุงเทพฯ",
        address: "253 ถนนสุขุมวิท 21 (อโศก) แขวงคลองเตยเหนือ",
        district: "วัฒนา",
        province: "กรุงเทพมหานคร",
        postal_code: "10110",
        latitude: 13.7372,
        longitude: 100.5621,
      },
      transit_time_from_prev_minutes: 8.0,
      distance_from_prev_km: 2.8,
      explanation: "จัดเข้าพบลำดับถัดไปที่อโศก ก่อนมุ่งหน้ากลับสู่พระราม 3 นำเสนอ Krungsri MRTA เพื่อปิดความเสี่ยงหนี้บ้าน 5.5 ล้านบาท",
    },
  ],
  ordered_stops: [
    {
      stop_order: 0,
      stop_type: "office_start",
      location_name: "ธนาคารกรุงศรีอยุธยา สำนักพระรามที่ 3 (สำนักงานใหญ่)",
      address: "1222 ถนนพระรามที่ 3 แขวงบางโพงพาง เขตยานนาวา กรุงเทพฯ 10120",
      latitude: 13.6827,
      longitude: 100.5478,
      meeting_duration_minutes: 0,
      travel_time_from_prev_minutes: 0,
      distance_from_prev_km: 0,
      customer: null,
      stop_reason: "จุดเริ่มต้นเดินทาง (Depot Start)",
    },
    {
      stop_order: 1,
      stop_type: "customer",
      location_name: "ณัฐชา 'เพิร์ล' ประเสริฐกิจการ (KS-00002)",
      address: "88 อาคารสาทรสแควร์ ถนนสาทรเหนือ แขวงสีลม",
      latitude: 13.7225,
      longitude: 100.5284,
      meeting_duration_minutes: 45,
      travel_time_from_prev_minutes: 14.0,
      distance_from_prev_km: 5.6,
      customer: null,
      stop_reason: "ลำดับที่ 1: ต่ออายุประกันรถยนต์ชั้น 1 ก่อนหมดอายุใน 21 วัน เพื่อรักษาส่วนลดประวัติดี 20%",
    },
    {
      stop_order: 2,
      stop_type: "customer",
      location_name: "ณัฐพร วาริน (KS-00001)",
      address: "99/1 ซอยทองหล่อ 10 แขวงคลองตันเหนือ",
      latitude: 13.7314,
      longitude: 100.5815,
      meeting_duration_minutes: 45,
      travel_time_from_prev_minutes: 18.0,
      distance_from_prev_km: 7.8,
      customer: null,
      stop_reason: "ลำดับที่ 2: กรมธรรม์สุขภาพ Krungsri Health Max 5M มีกำหนดต่ออายุใน 14 วัน เสนอ CI Protect",
    },
    {
      stop_order: 3,
      stop_type: "customer",
      location_name: "วิภา ชัยโย (KS-00004)",
      address: "253 ถนนสุขุมวิท 21 (อโศก) แขวงคลองเตยเหนือ",
      latitude: 13.7372,
      longitude: 100.5621,
      meeting_duration_minutes: 45,
      travel_time_from_prev_minutes: 8.0,
      distance_from_prev_km: 2.8,
      customer: null,
      stop_reason: "ลำดับที่ 3: ปิดความเสี่ยงภาระหนี้สินเชื่อบ้าน 5.5 ล้านบาท ด้วย Krungsri MRTA",
    },
    {
      stop_order: 4,
      stop_type: "office_end",
      location_name: "ธนาคารกรุงศรีอยุธยา สำนักพระรามที่ 3 (สำนักงานใหญ่)",
      address: "1222 ถนนพระรามที่ 3 แขวงบางโพงพาง เขตยานนาวา กรุงเทพฯ 10120",
      latitude: 13.6827,
      longitude: 100.5478,
      meeting_duration_minutes: 0,
      travel_time_from_prev_minutes: 12.0,
      distance_from_prev_km: 5.6,
      customer: null,
      stop_reason: "จุดสิ้นสุดเดินทางกลับสำนักงาน (Depot Return)",
    },
  ],
  violated_constraints: [],
  suggested_deferrals: [],
  explanations: [
    "จัดลำดับเริ่มจาก ณัฐชา 'เพิร์ล' ประเสริฐกิจการ (KS-00002) ตามความเร่งด่วนสูงสุด (ประกันรถยนต์หมดใน 21 วัน, Score 94)",
    "จัดเข้าพบต่อเนื่อง ณัฐพร วาริน (KS-00001) ที่ทองหล่อเพื่อทบทวนต่ออายุสุขภาพและเสนอ CI Protect ก่อนครบกำหนด 14 วัน",
    "จัดเข้าพบ วิภา ชัยโย (KS-00004) ที่อโศก เพื่อนำเสนอ Krungsri MRTA คุ้มครองวงเงินสินเชื่อบ้าน 5.5 ล้านบาท",
    "จัดลำดับเส้นทางแบบวงรอบต่อเนื่อง (Loop Route: พระราม 3 → สาทร → ทองหล่อ → อโศก → พระราม 3) เพื่อลดการจราจรติดขัดและประหยัดเวลา",
    "เส้นทางผ่านเกณฑ์ข้อกำหนดทั้งหมด: ระยะทางรวม 21.8 กม. (ขีดจำกัด 60.0 กม.), เวลาเดินทาง 52 นาที (ขีดจำกัด 150 นาที)",
  ],
  optimization_summary: {
    priority_influence: "จัดลำดับลูกค้าโดยให้น้ำหนักความสำคัญและสถานะความเร่งด่วนควบคู่กับเส้นทางที่มีประสิทธิภาพสูงสุด (High Priority First)",
    urgency_influence: "ตรวจพบลูกค้าที่มีจังหวะเวลาเร่งด่วน (ณัฐชา: ประกันรถยนต์หมดใน 21 วัน, ณัฐพร: สุขภาพหมดใน 14 วัน) ได้รับการจัดเข้าพบในวันนี้",
    efficiency_influence: "จัดเส้นทางแบบวงรอบต่อเนื่อง (Loop Route) รวมระยะทาง 21.8 กม. และเวลาเดินทาง 52 นาที ประหยัดเวลาได้กว่า 38% เมื่อเทียบกับการเดินทางแบบกระจาย",
  },
  unroutable_customers: [],
};

// ── Phase 12 Analytics Mock Data (Production-Ready for Vercel / Standalone Preview) ──

export const MOCK_ANALYTICS_OVERVIEW: AnalyticsOverviewResponse = {
  role_scope: "broker",
  user_name: "สมชาย ใจดี (Krungsri Certified Broker)",
  total_customers: 248,
  high_priority_customers: 42,
  medium_priority_customers: 118,
  low_priority_customers: 88,
  follow_ups_due: 18,
  follow_ups_completed: 232,
  follow_ups_overdue: 3,
  ai_analysis_count: 248,
  recommendation_count: 258,
  approval_rate: 68.8,
  modification_rate: 19.2,
  rejection_rate: 12.0,
  as_of: new Date().toISOString(),
};

export const MOCK_ANALYTICS_PRIORITY: PriorityAnalyticsResponse = {
  role_scope: "broker",
  total_scored_customers: 248,
  priority_distribution: {
    high: 42,
    medium: 118,
    low: 88,
  },
  average_priority_score: 48.5,
  score_distribution: [
    { bucket: "0-20 (ต่ำมาก)", count: 27, percentage: 10.9 },
    { bucket: "21-40 (ต่ำ)", count: 95, percentage: 38.3 },
    { bucket: "41-60 (ปานกลาง)", count: 64, percentage: 25.8 },
    { bucket: "61-80 (สูง)", count: 45, percentage: 18.1 },
    { bucket: "81-100 (สูงมาก)", count: 17, percentage: 6.9 },
  ],
  priority_trends: [
    { period: "W-3", high: 12, medium: 30, low: 25 },
    { period: "W-2", high: 18, medium: 35, low: 28 },
    { period: "W-1", high: 28, medium: 42, low: 32 },
    { period: "สัปดาห์ปัจจุบัน (This Week)", high: 42, medium: 118, low: 88 },
  ],
  as_of: new Date().toISOString(),
};

export const MOCK_ANALYTICS_NEEDS: NeedAnalyticsResponse = {
  role_scope: "broker",
  total_needs_identified: 258,
  categories_distribution: [
    {
      category: "Health protection",
      label_th: "ความคุ้มครองสุขภาพและโรคร้ายแรง",
      count: 103,
      percentage: 39.9,
    },
    {
      category: "Financial protection",
      label_th: "การคุ้มครองสินเชื่อและภาระหนี้",
      count: 101,
      percentage: 39.1,
    },
    {
      category: "Retirement planning",
      label_th: "การวางแผนเกษียณและออมระยะยาว",
      count: 43,
      percentage: 16.7,
    },
    {
      category: "Coverage review",
      label_th: "การทบทวนและต่ออายุกรมธรรม์",
      count: 8,
      percentage: 3.1,
    },
    {
      category: "Life protection",
      label_th: "ความคุ้มครองชีวิตและภาระครอบครัว",
      count: 3,
      percentage: 1.2,
    },
  ],
  top_identified_needs: [
    {
      description: "แนะนำความคุ้มครองสุขภาพแบบเหมาจ่ายและโรคร้ายแรงระยะวิกฤตเพื่อรองรับค่ารักษาพยาบาลที่ปรับตัวสูงขึ้น",
      count: 101,
    },
    {
      description: "ลูกค้ากลุ่มวัยทำงานและผู้มีภาระสินเชื่อบ้าน ทบทวนทุนประกันคุ้มครองวงเงินสินเชื่อ",
      count: 45,
    },
    {
      description: "ลูกค้าวัย 45+ เตรียมความพร้อมทางการเงินเพื่อสร้างเงินบำนาญและรักษาสภาพคล่องหลังเกษียณ",
      count: 28,
    },
  ],
  as_of: new Date().toISOString(),
};

export const MOCK_ANALYTICS_RECOMMENDATIONS: RecommendationAnalyticsResponse = {
  total_recommendations: 258,
  total_decisions: 250,
  approval_count: 172,
  approval_rate: 68.8,
  modification_count: 48,
  modification_rate: 19.2,
  rejection_count: 30,
  rejection_rate: 12.0,
  recommendations_by_category: {
    Health: 103,
    Protection: 101,
    Retirement: 43,
    Life: 8,
    Motor: 3,
  },
  common_modification_reasons: {
    "ปรับให้เหมาะกับงบประมาณ": 48,
    "ลูกค้าต้องการปรับระยะเวลาคุ้มครอง": 24,
  },
  common_rejection_reasons: {
    "ปรับให้เหมาะกับงบประมาณ": 30,
    "มีกรมธรรม์ลักษณะเดียวกันแล้ว": 12,
  },
  common_approval_reasons: {
    "สอดคล้องกับความต้องการลูกค้า": 172,
    "ปิด Gap ความคุ้มครองชัดเจน": 86,
  },
  as_of: new Date().toISOString(),
};

export const MOCK_ANALYTICS_FOLLOWUPS: FollowUpAnalyticsResponse = {
  role_scope: "broker",
  total_follow_ups: 250,
  due_count: 18,
  completed_count: 232,
  overdue_count: 3,
  upcoming_count: 15,
  status_distribution: {
    open: 18,
    done: 232,
    snoozed: 0,
  },
  payment_status_distribution: {
    paid: 247,
    overdue: 3,
    pending: 0,
  },
  as_of: new Date().toISOString(),
};

export const MOCK_ANALYTICS_AI_USAGE: AIUsageAnalyticsResponse = {
  role_scope: "broker",
  active_model_version: "1.0.0",
  model_name: "LightGBM Priority Classifier",
  total_ai_scoring_requests: 250,
  total_llm_insight_requests: 250,
  total_conversation_requests: 189,
  total_feedback_recorded: 42,
  feedback_breakdown: {
    useful: 38,
    not_useful: 2,
    incorrect: 1,
    needs_review: 1,
  },
  as_of: new Date().toISOString(),
};

export const MOCK_AUDIT_LOGS = [
  {
    id: "aud-001",
    user_id: "u-broker-1",
    action: "recommendation.approve",
    entity_type: "recommendation",
    entity_id: "rec-ks-00001-1",
    metadata: {
      customer_id: "d82e838c-63fb-47a3-9428-f15dc4d68883",
      customer_ref: "KS-00001",
      product_name: "กรุงศรี สุขภาพพรีเมียม พลัส (เหมาจ่าย)",
      reason: "สอดคล้องกับความต้องการลูกค้า",
    },
    timestamp: "2026-09-12T16:20:00Z",
  },
  {
    id: "aud-002",
    user_id: "u-broker-1",
    action: "ai.score_generate",
    entity_type: "customer",
    entity_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
    metadata: {
      customer_ref: "KS-00002",
      model: "LightGBM Priority Classifier v1.0",
      priority_score: 94,
      priority_level: "high",
    },
    timestamp: "2026-09-12T15:45:00Z",
  },
  {
    id: "aud-003",
    user_id: "u-broker-1",
    action: "visit_planner.route_create",
    entity_type: "visit_route",
    entity_id: "route-20260912",
    metadata: {
      total_stops: 3,
      total_distance_km: 18.4,
      transport: "car",
    },
    timestamp: "2026-09-12T14:30:00Z",
  },
  {
    id: "aud-004",
    user_id: "u-admin-1",
    action: "compliance.export_audit",
    entity_type: "compliance_report",
    entity_id: "rep-20260912",
    metadata: {
      export_format: "csv",
      filter_role: "broker",
      records_exported: 250,
    },
    timestamp: "2026-09-12T13:00:00Z",
  },
  {
    id: "aud-005",
    user_id: "u-broker-1",
    action: "user.login",
    entity_type: "auth",
    entity_id: "sess-01",
    metadata: {
      email: "broker@demo.local",
      ip: "127.0.0.1",
      device: "Desktop Safari",
    },
    timestamp: "2026-09-12T08:30:00Z",
  },
];

