import type { CandidateCustomerOut, LocationPoint } from "@/types";

export interface NearbyKPIStats {
  totalNearby: number;
  highPriorityCount: number;
  followUpWithin7DaysCount: number;
  kycCount: number;
  recommendationOpportunityCount: number;
}

export const DEFAULT_BROKER_LOCATION: LocationPoint = {
  name: "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าลาดกระบัง, กรุงเทพฯ",
  address: "1 ซอยฉลองกรุง 1 แขวงลาดกระบัง เขตลาดกระบัง กรุงเทพมหานคร 10520",
  latitude: 13.7299,
  longitude: 100.7782,
};

export const AVAILABLE_LOCATION_PRESETS: LocationPoint[] = [
  {
    name: "มหาวิทยาลัยเทคโนโลยีพระจอมเกล้าลาดกระบัง, กรุงเทพฯ",
    address: "1 ซอยฉลองกรุง 1 แขวงลาดกระบัง เขตลาดกระบัง กรุงเทพมหานคร 10520",
    latitude: 13.7299,
    longitude: 100.7782,
  },
  {
    name: "ธนาคารกรุงศรีอยุธยา สำนักพระรามที่ 3 (สำนักงานใหญ่)",
    address: "1222 ถนนพระรามที่ 3 แขวงบางโพงพาง เขตยานนาวา กรุงเทพมหานคร 10120",
    latitude: 13.6827,
    longitude: 100.5478,
  },
  {
    name: "ธนาคารกรุงศรีอยุธยา สาขาสยามพารากอน",
    address: "991 ถนนพระรามที่ 1 แขวงปทุมวัน เขตปทุมวัน กรุงเทพมหานคร 10330",
    latitude: 13.7460,
    longitude: 100.5348,
  },
  {
    name: "ธนาคารกรุงศรีอยุธยา สาขาไอคอนสยาม",
    address: "299 ถนนเจริญนคร แขวงคลองต้นไทร เขตคลองสาน กรุงเทพมหานคร 10600",
    latitude: 13.7267,
    longitude: 100.5108,
  },
];

export const SHOWCASE_KPI_STATS: NearbyKPIStats = {
  totalNearby: 128,
  highPriorityCount: 28,
  followUpWithin7DaysCount: 17,
  kycCount: 72,
  recommendationOpportunityCount: 86,
};

export const SHOWCASE_NEARBY_CUSTOMERS: CandidateCustomerOut[] = [
  {
    customer_id: "c0c0f992-b06d-4b9f-bbc6-9b4458a79491",
    external_ref: "KS-00002",
    customer_name: "ณัฐชา 'เพิร์ล' ประเสริฐกิจการ",
    display_name: "ณัฐชา 'เพิร์ล' ประเสริฐกิจการ (KS-00002)",
    age: 26,
    occupation: "UX/UI Designer (Tech Startup)",
    address: "ซ.ลาดกระบัง 24/3, กรุงเทพฯ",
    district: "เขตลาดกระบัง",
    province: "กรุงเทพมหานคร",
    latitude: 13.7380,
    longitude: 100.7845,
    distance_km: 2.1,
    location_available: true,
    routable: true,
    priority_score: 94,
    priority_level: "high",
    kyc_status: "verified",
    relationship_tier: "Silver",
    active_policies_count: 2,
    phone: "089-456-7890",
    email: "natcha.p@pearlstudio.design",
    product_tags: ["Motor (รถยนต์)", "Health (สุขภาพ)", "Savings (ออมเงิน)"],
    why_now: "ประกันภัยรถยนต์ Type 1 ครบกำหนดต่ออายุใน 21 วัน และมีช่องว่างประกันสุขภาพ",
    recommended_next_action: "ติดต่อแนะนำแพ็กเกจร่วม Motor Type 1 + Health Top-up",
    contact_history: {
      last_call: "3 ก.ย. 2569",
      last_call_detail: "สนใจประกันรถยนต์และสอบถามเบี้ยสุขภาพ",
      appointment: "10 ก.ย. 2569",
      appointment_detail: "ที่ร้านกาแฟ (รอยืนยัน)",
      sent_doc: "28 ส.ค. 2569",
      sent_doc_detail: "ใบเสนอราคา Motor Type 1",
    },
    ai_note: "ลูกค้ามีแนวโน้มตัดสินใจสูง แนะนำติดต่อภายใน 7 วัน และนำเสนอ Package ร่วม Motor + Health",
  },
  {
    customer_id: "d82e838c-63fb-47a3-9428-f15dc4d68883",
    external_ref: "KS-00001",
    customer_name: "ณัฐพร วาริน",
    display_name: "ณัฐพร วาริน (KS-00001)",
    age: 42,
    occupation: "กรรมการผู้จัดการ บจก. เมดิเทค อินโนเวชั่น",
    address: "ถ.ร่มเกล้า แขวงคลองสามประเวศ, กรุงเทพฯ",
    district: "เขตลาดกระบัง",
    province: "กรุงเทพมหานคร",
    latitude: 13.7460,
    longitude: 100.7550,
    distance_km: 3.4,
    location_available: true,
    routable: true,
    priority_score: 92,
    priority_level: "high",
    kyc_status: "verified",
    relationship_tier: "Platinum",
    active_policies_count: 3,
    phone: "081-823-4567",
    email: "nattaporn.w@meditech.co.th",
    product_tags: ["Health", "Savings"],
    why_now: "ประกันสุขภาพหลัก Health Max 5M ใกล้ครบกำหนดต่ออายุใน 14 วัน และยังขาดความคุ้มครองโรคร้ายแรง (CI)",
    recommended_next_action: "ประสานงานต่ออายุประกันสุขภาพพร้อมเสริมความคุ้มครองโรคร้ายแรง",
    contact_history: {
      last_call: "5 ก.ย. 2569",
      last_call_detail: "แจ้งเตือนต่ออายุประกันสุขภาพ",
      appointment: "12 ก.ย. 2569",
      appointment_detail: "สาขากรุงศรีพระราม 3",
      sent_doc: "1 ก.ย. 2569",
      sent_doc_detail: "เอกสารสรุปความคุ้มครองเดิม",
    },
    ai_note: "ลูกค้าต้องการความคุ้มครองต่อเนื่อง มีโอกาสต่ออายุสูงมากและพร้อมอัปเกรดค่าห้อง",
  },
  {
    customer_id: "c0a451ce-a2b5-406e-9358-4a2af87721ca",
    external_ref: "KS-00004",
    customer_name: "วิภา ชัยโย",
    display_name: "วิภา ชัยโย (KS-00004)",
    age: 38,
    occupation: "ผู้จัดการฝ่ายจัดซื้อ บจก. ไทยคอมเมิร์ซ",
    address: "ถ.สุวรรณภูมิ 1 แขวงหนองปรือ, สมุทรปราการ",
    district: "เขตบางพลี",
    province: "สมุทรปราการ",
    latitude: 13.7080,
    longitude: 100.7500,
    distance_km: 4.2,
    location_available: true,
    routable: true,
    priority_score: 76,
    priority_level: "medium",
    kyc_status: "verified",
    relationship_tier: "Gold",
    active_policies_count: 1,
    phone: "089-123-4567",
    email: "wipa.c@thaicommerce.co.th",
    product_tags: ["Protection"],
    why_now: "เพิ่งได้รับอนุมัติสินเชื่อบ้าน 5.5M มีความเสี่ยงวงเงินคุ้มครองหนี้ (MRTA)",
    recommended_next_action: "ทบทวนทุนประกันชีวิตคุ้มครองวงเงินสินเชื่อบ้าน",
    contact_history: {
      last_call: "28 ส.ค. 2569",
      last_call_detail: "ยินดีกับสินเชื่อบ้านใหม่",
      appointment: "15 ก.ย. 2569",
      appointment_detail: "นัดโทรคุยรายละเอียด",
      sent_doc: "2 ก.ย. 2569",
      sent_doc_detail: "ตารางเปรียบเทียบเบี้ย MRTA",
    },
    ai_note: "ลูกค้ากังวลเรื่องภาระหนี้สิน แนะนำแผนคุ้มครองสินเชื่อระยะยาว",
  },
  {
    customer_id: "f535562e-8f70-4711-bbd0-7e092606cdd7",
    external_ref: "KS-00005",
    customer_name: "ธนภูมิ ยิ้มแย้ม",
    display_name: "ธนภูมิ ยิ้มแย้ม (KS-00005)",
    age: 52,
    occupation: "รองกรรมการผู้จัดการ (COO) บมจ. ฟู้ดคอร์ปอเรชั่น",
    address: "ถ.ฉลองกรุง แขวงลำปลาทิว, กรุงเทพฯ",
    district: "เขตลาดกระบัง",
    province: "กรุงเทพมหานคร",
    latitude: 13.7650,
    longitude: 100.7950,
    distance_km: 5.6,
    location_available: true,
    routable: true,
    priority_score: 65,
    priority_level: "medium",
    kyc_status: "verified",
    relationship_tier: "Platinum",
    active_policies_count: 4,
    phone: "085-789-0123",
    email: "thanapoom.y@foodcorp.co.th",
    product_tags: ["AUM", "Pension"],
    why_now: "เงินฝาก AUM 14.2M ต้องการวางแผนลดหย่อนภาษีบำนาญ Smart Pension",
    recommended_next_action: "นัดหมายปรึกษาการออมแบบบำนาญลดหย่อนภาษีปลายปี",
    contact_history: {
      last_call: "1 ก.ย. 2569",
      last_call_detail: "สอบถามสิทธิประโยชน์ภาษี",
      appointment: "18 ก.ย. 2569",
      appointment_detail: "สาขากรุงศรี ลาดกระบัง",
      sent_doc: "3 ก.ย. 2569",
      sent_doc_detail: "โบรชัวร์ Krungsri Smart Pension 85/60",
    },
    ai_note: "มีฐานะการเงินมั่นคงสูง เหมาะกับแบบประกันบำนาญและประกันชีวิตควบการลงทุน",
  },
  {
    customer_id: "0dd17657-a534-4f57-836c-26d73cc0c2e5",
    external_ref: "KS-00006",
    customer_name: "วิภา รุ่งเรือง",
    display_name: "วิภา รุ่งเรือง (KS-00006)",
    age: 31,
    occupation: "สถาปนิกอิสระ (Freelance Architect)",
    address: "ถ.กิ่งแก้ว ต.ราชาเทวะ, สมุทรปราการ",
    district: "เขตบางพลี",
    province: "สมุทรปราการ",
    latitude: 13.7120,
    longitude: 100.7250,
    distance_km: 6.1,
    location_available: true,
    routable: true,
    priority_score: 62,
    priority_level: "medium",
    kyc_status: "pending",
    relationship_tier: "Standard",
    active_policies_count: 1,
    phone: "086-234-5678",
    email: "wipa.r@designstudio.in.th",
    product_tags: ["Savings", "Health"],
    why_now: "อยู่ระหว่างรอยืนยัน KYC และต้องการออมเงินระยะสั้นผลตอบแทนแน่นอน",
    recommended_next_action: "ติดตามการยืนยันตัวตน KYC พร้อมแนะนำ Krungsri Savings 10/5",
    contact_history: {
      last_call: "25 ส.ค. 2569",
      last_call_detail: "แจ้งขั้นตอนการยืนยัน KYC ผ่าน KMA",
      appointment: "20 ก.ย. 2569",
      appointment_detail: "รอติดต่อกลับหลังส่งเอกสาร",
      sent_doc: "27 ส.ค. 2569",
      sent_doc_detail: "รายละเอียด Krungsri Savings 10/5",
    },
    ai_note: "เป็นลูกค้าใหม่ที่รอการยืนยันตัวตน สนใจการออมที่ให้เงินคืนรายปีสม่ำเสมอ",
  },
  {
    customer_id: "73684349-2be5-442a-aa25-373938e4a3f2",
    external_ref: "KS-00007",
    customer_name: "อานนท์ ก้าวหน้า",
    display_name: "อานนท์ ก้าวหน้า (KS-00007)",
    age: 45,
    occupation: "เจ้าของกิจการ ค้าส่งสินค้าอุปโภคบริโภค",
    address: "ถ.เจ้าคุณทหาร แขวงลำปลาทิว, กรุงเทพฯ",
    district: "เขตลาดกระบัง",
    province: "กรุงเทพมหานคร",
    latitude: 13.7550,
    longitude: 100.7880,
    distance_km: 6.8,
    location_available: true,
    routable: true,
    priority_score: 58,
    priority_level: "medium",
    kyc_status: "verified",
    relationship_tier: "Gold",
    active_policies_count: 2,
    phone: "084-567-8901",
    email: "arnon.k@kawnah-sme.com",
    product_tags: ["Protection", "Loan"],
    why_now: "สินเชื่อ SME OD 2.5M และกรมธรรม์ Life Plus ครบกำหนดต่ออายุใน 20 วัน",
    recommended_next_action: "ติดต่อต่ออายุ Life Plus พร้อมทบทวนความคุ้มครองสินเชื่อหมุนเวียนธุรกิจ",
    contact_history: {
      last_call: "20 ส.ค. 2569",
      last_call_detail: "ปรึกษาแผนคุ้มครองสินเชื่อธุรกิจ",
      appointment: "22 ก.ย. 2569",
      appointment_detail: "นัดพบที่คลังสินค้าเจ้าคุณทหาร",
      sent_doc: "22 ส.ค. 2569",
      sent_doc_detail: "ตารางสรุปเบี้ย Life Plus",
    },
    ai_note: "ลูกค้าต้องการความคุ้มครองที่ยืดหยุ่นเพื่อปกป้องสภาพคล่องของธุรกิจ SME",
  },
  {
    customer_id: "0d76a238-a48a-40bd-8ebb-0051fea69f3f",
    external_ref: "KS-00008",
    customer_name: "ณัฐพร ทวีผล",
    display_name: "ณัฐพร ทวีผล (KS-00008)",
    age: 68,
    occupation: "ข้าราชการบำนาญ (อดีตอาจารย์)",
    address: "ถ.พัฒนาการตัดใหม่ แขวงประเวศ, กรุงเทพฯ",
    district: "เขตประเวศ",
    province: "กรุงเทพมหานคร",
    latitude: 13.7220,
    longitude: 100.7100,
    distance_km: 7.3,
    location_available: true,
    routable: true,
    priority_score: 55,
    priority_level: "low",
    kyc_status: "verified",
    relationship_tier: "Standard",
    active_policies_count: 1,
    phone: "083-901-2345",
    email: "nattaporn.t@thaiedu.mail",
    product_tags: ["Senior Protection", "Legacy"],
    why_now: "ผ่านเกณฑ์ Hard-Gating ผู้สูงอายุ 68 ปี ต้องการวางแผนส่งต่อมรดกให้บุตรหลาน",
    recommended_next_action: "นำเสนอประกันชีวิตเพื่อการส่งต่อมรดกสำหรับผู้สูงอายุ (Senior Life)",
    contact_history: {
      last_call: "15 ส.ค. 2569",
      last_call_detail: "สอบถามเงื่อนไขการทำประกันวัยเกษียณ",
      appointment: "25 ก.ย. 2569",
      appointment_detail: "โทรติดตามผลหลังคุยกับลูกสาว",
      sent_doc: "18 ส.ค. 2569",
      sent_doc_detail: "เอกสารคุ้มครองมรดกผู้สูงอายุ",
    },
    ai_note: "ผ่านการประเมิน Vulnerable Customer และ Hard-Gating เรียบร้อย แนะนำให้สื่อสารด้วยความชัดเจน",
  },
  {
    customer_id: "9f8e7d6c-5b4a-3f2e-1d0c-9b8a7f6e5d4c",
    external_ref: "KS-00009",
    customer_name: "ปรีชา จันทร์ดี",
    display_name: "ปรีชา จันทร์ดี (KS-00009)",
    age: 30,
    occupation: "ผู้จัดการสาขาร้านอาหาร",
    address: "ถ.อ่อนนุช แขวงลาดกระบัง, กรุงเทพฯ",
    district: "เขตลาดกระบัง",
    province: "กรุงเทพมหานคร",
    latitude: 13.7190,
    longitude: 100.7600,
    distance_km: 8.1,
    location_available: true,
    routable: true,
    priority_score: 52,
    priority_level: "low",
    kyc_status: "pending",
    relationship_tier: "Standard",
    active_policies_count: 1,
    phone: "082-345-6789",
    email: "preecha.c@bkkdining.co.th",
    product_tags: ["Loan"],
    why_now: "กำลังขยายสาขา ต้องการวงเงินสินเชื่อหมุนเวียนธุรกิจ SME",
    recommended_next_action: "แนะนำติดต่อทีมสินเชื่อธุรกิจกรุงศรีและวางแผนคุ้มครองเจ้าของกิจการ",
    contact_history: {
      last_call: "10 ส.ค. 2569",
      last_call_detail: "ปรึกษาวงเงินสินเชื่อ SME",
      appointment: "28 ก.ย. 2569",
      appointment_detail: "นัดพบที่ร้านสาขาอ่อนนุช",
      sent_doc: "12 ส.ค. 2569",
      sent_doc_detail: "รายการเอกสารยื่นกู้สินเชื่อ SME",
    },
    ai_note: "กำลังขยายธุรกิจ มีโอกาสนำเสนอ Keyman Insurance ในอนาคต",
  },
  {
    customer_id: "8e7d6c5b-4a3f-2e1d-0c9b-8a7f6e5d4c3b",
    external_ref: "KS-00010",
    customer_name: "เดชา สิงห์ทอง",
    display_name: "เดชา สิงห์ทอง (KS-00010)",
    age: 26,
    occupation: "Content Creator & Youtuber",
    address: "ถ.ศรีนครินทร์ แขวงสวนหลวง, กรุงเทพฯ",
    district: "เขตสวนหลวง",
    province: "กรุงเทพมหานคร",
    latitude: 13.7320,
    longitude: 100.6900,
    distance_km: 8.7,
    location_available: true,
    routable: true,
    priority_score: 48,
    priority_level: "low",
    kyc_status: "verified",
    relationship_tier: "Silver",
    active_policies_count: 1,
    phone: "087-654-3210",
    email: "decha.s@creativestudio.tv",
    product_tags: ["Health"],
    why_now: "ประกอบอาชีพอิสระ ไม่มีสวัสดิการประกันกลุ่มจากบริษัท",
    recommended_next_action: "ส่งลิงก์ดูแผนประกัน My Protection แผนเหมาจ่าย Gen Z",
    contact_history: {
      last_call: "5 ส.ค. 2569",
      last_call_detail: "แนะนำแผนเหมาจ่าย Extra Care",
      appointment: "29 ก.ย. 2569",
      appointment_detail: "ทักแชทสอบถามทาง LINE",
      sent_doc: "6 ส.ค. 2569",
      sent_doc_detail: "สรุปเบี้ยรายเดือนแผน Gen Z",
    },
    ai_note: "ชอบชำระเบี้ยแบบรายเดือนผ่าน KMA แนะนำแผนความคุ้มครองที่ปรับเปลี่ยนได้ตามรายได้",
  },
  {
    customer_id: "7d6c5b4a-3f2e-1d0c-9b8a-7f6e5d4c3b2a",
    external_ref: "KS-00011",
    customer_name: "เอกสิทธิ์ วัฒนะ",
    display_name: "เอกสิทธิ์ วัฒนะ (KS-00011)",
    age: 38,
    occupation: "หัวหน้าฝ่ายโลจิสติกส์",
    address: "ถ.บางนา-ตราด กม.12 ต.บางพลีใหญ่, สมุทรปราการ",
    district: "เขตบางพลี",
    province: "สมุทรปราการ",
    latitude: 13.6890,
    longitude: 100.7100,
    distance_km: 9.4,
    location_available: true,
    routable: true,
    priority_score: 45,
    priority_level: "low",
    kyc_status: "verified",
    relationship_tier: "Standard",
    active_policies_count: 2,
    phone: "088-901-2345",
    email: "ekkasit.w@thaiairfreight.com",
    product_tags: ["Pension"],
    why_now: "เริ่มวางแผนเกษียณอายุ มีกองทุนสำรองเลี้ยงชีพอยู่แล้ว",
    recommended_next_action: "คำนวณเงินบำนาญเพิ่มเติมหลังอายุ 60 ปี",
    contact_history: {
      last_call: "1 ส.ค. 2569",
      last_call_detail: "สอบถามกองทุนลดหย่อนภาษี",
      appointment: "30 ก.ย. 2569",
      appointment_detail: "รอติดต่อกลับช่วงปลายไตรมาส",
      sent_doc: "3 ส.ค. 2569",
      sent_doc_detail: "ตารางประมาณการเงินเกษียณ",
    },
    ai_note: "เน้นการออมระยะยาวควบคู่กับการลดหย่อนภาษีบุคคลธรรมดา",
  },
];
