export interface TourStep {
  id: string;
  stepNumber: number;
  title: string;
  description: string;
  route?: string;
  targetSelector?: string;
  placement?: "top" | "bottom" | "left" | "right" | "center";
  roles: ("broker" | "manager" | "admin")[];
  tag?: string;
  icon?: string;
  keyHighlight?: string;
}

export interface FeatureCatalogItem {
  id: string;
  title: string;
  subtitle: string;
  icon: string;
  route: string;
  stepIndex: number;
  tag: string;
  highlights: string[];
}

export const BROKER_TOUR_STEPS: TourStep[] = [
  {
    id: "broker-dashboard",
    stepNumber: 1,
    title: "แดชบอร์ด",
    description: "ดูภาพรวมลูกค้า งานติดตาม และสิ่งที่ควรให้ความสนใจได้จากหน้าเดียว",
    route: "/dashboard",
    targetSelector: '[data-tour="dashboard"], [data-tour="dashboard-overview"]',
    placement: "bottom",
    roles: ["broker"],
    tag: "Dashboard",
    icon: "🏠",
    keyHighlight: "⚡ รวมลูกค้าด่วนประจำวัน งานติดตาม และคำแนะนำกลยุทธ์จาก AI ไว้ในหน้าเดียว",
  },
  {
    id: "broker-customers",
    stepNumber: 2,
    title: "ฐานข้อมูลลูกค้า",
    description: "ค้นหาและกรองลูกค้าตามข้อมูลและ Priority เพื่อค้นหาลูกค้าที่ต้องการได้รวดเร็วขึ้น",
    route: "/customers",
    targetSelector: '[data-tour="customers"], [data-tour="customer-table"]',
    placement: "top",
    roles: ["broker"],
    tag: "Customer Directory",
    icon: "👥",
    keyHighlight: "🔍 กรองลูกค้าตามระดับความเร่งด่วนและประเภทกรมธรรม์ที่ต้องการได้ทันที",
  },
  {
    id: "broker-customer-360",
    stepNumber: 3,
    title: "Customer 360°",
    description: "ดูข้อมูลลูกค้าในมุมมองเดียว ทั้งข้อมูลส่วนตัว สินทรัพย์ ภาระ กรมธรรม์ และบริบทที่เกี่ยวข้อง",
    route: "/customers/KS-00001",
    targetSelector: '[data-tour="customer-360"], [data-tour="customer-profile-header"]',
    placement: "bottom",
    roles: ["broker"],
    tag: "Customer 360°",
    icon: "👤",
    keyHighlight: "📋 รวมข้อมูลรอบด้าน 5 มิติ ไม่ต้องเสียเวลาเปิดหาจากหลายระบบ",
  },
  {
    id: "broker-ai-insight",
    stepNumber: 4,
    title: "AI ช่วยจัดลำดับความสำคัญ",
    description: "AI ช่วยวิเคราะห์ Priority และแสดง Why Now เพื่อช่วยให้นายหน้ารู้ว่าลูกค้ารายไหนควรให้ความสนใจ",
    route: "/customers/KS-00001",
    targetSelector: '[data-tour="ai-insight"], [data-tour="ai-priority-card"]',
    placement: "left",
    roles: ["broker"],
    tag: "TreeSHAP Explainability",
    icon: "🧠",
    keyHighlight: "💡 เข้าใจเหตุผลความเร่งด่วน พร้อมคำอธิบายปัจจัยสำคัญแบบโปร่งใส ไร้กล่องดำ",
  },
  {
    id: "broker-recommendations",
    stepNumber: 5,
    title: "คำแนะนำสำหรับลูกค้า",
    description: "ระบบช่วยตรวจสอบ Eligibility และวิเคราะห์ความต้องการก่อนเสนอคำแนะนำ โดยนายหน้ายังคงเป็นผู้ตัดสินใจ",
    route: "/customers/KS-00001",
    targetSelector: '[data-tour="recommendation"], [data-tour="product-recommendations"]',
    placement: "top",
    roles: ["broker"],
    tag: "Hard Eligibility Gate",
    icon: "🛡️",
    keyHighlight: "✅ กรองเงื่อนไขตายตัว 100% ป้องกันข้อเสนอผิดเกณฑ์ พร้อมเปิดให้นายหน้าตัดสินใจเอง",
  },
  {
    id: "broker-nearby",
    stepNumber: 6,
    title: "ลูกค้าใกล้เคียง",
    description: "ค้นหาลูกค้าที่อยู่ใกล้ตำแหน่งปัจจุบัน พร้อมดู Priority, Why Now และระยะทาง",
    route: "/visit-planner",
    targetSelector: '[data-tour="nearby-customers"], [data-tour="nearby-customers-map"]',
    placement: "right",
    roles: ["broker"],
    tag: "Proximity Map",
    icon: "📍",
    keyHighlight: "🗺️ แผนที่ Proximity Map เรดาร์พิกัดจริง ช่วยให้นายหน้าเข้าพบลูกค้าที่อยู่ใกล้ได้ทันเวลา",
  },
  {
    id: "broker-manual-selection",
    stepNumber: 7,
    title: "คุณเป็นคนเลือก",
    description: "AI ช่วยแสดงข้อมูลประกอบการตัดสินใจ แต่คุณเป็นผู้เลือกเองว่าจะไปพบลูกค้ารายใด",
    route: "/visit-planner",
    targetSelector: '[data-tour="customer-selection"], [data-tour="customer-selection-action"]',
    placement: "left",
    roles: ["broker"],
    tag: "Broker Decision",
    icon: "✋",
    keyHighlight: "⚖️ นายหน้าเป็นผู้ตัดสินใจขั้นสุดท้ายเสมอ (Human-in-the-Loop Discretion)",
  },
  {
    id: "broker-navigation",
    stepNumber: 8,
    title: "นำทางเมื่อต้องการ",
    description: "เมื่อคุณเลือกลูกค้าแล้ว ระบบจะแสดงเส้นทางจากตำแหน่งปัจจุบันไปยังลูกค้ารายนั้น",
    route: "/visit-planner",
    targetSelector: '[data-tour="navigation"], [data-tour="navigation-preview-action"]',
    placement: "top",
    roles: ["broker"],
    tag: "On-Demand Navigation",
    icon: "🧭",
    keyHighlight: "🚗 แสดงเส้นทางนำทางจริงแบบ On-Demand เมื่อนายหน้าพร้อมออกเดินทาง",
  },
  {
    id: "broker-analytics",
    stepNumber: 9,
    title: "Analytics",
    description: "ดูภาพรวมและข้อมูลวิเคราะห์เพื่อช่วยติดตามผลการทำงาน",
    route: "/analytics",
    targetSelector: '[data-tour="analytics"], [data-tour="analytics-overview"]',
    placement: "bottom",
    roles: ["broker"],
    tag: "Analytics & Governance",
    icon: "📊",
    keyHighlight: "📈 ติดตามความคุ้มค่าและภาพรวมการเติบโตของพอร์ตโฟลิโอได้อย่างแม่นยำ",
  },
];

export const MANAGER_TOUR_STEPS: TourStep[] = [
  {
    id: "manager-dashboard",
    stepNumber: 1,
    title: "แดชบอร์ดภาพรวมการดำเนินงาน",
    description: "ติดตามภาพรวมประสิทธิภาพการทำงานของทีม สถิติลูกค้ากลุ่มเป้าหมาย และเป้าหมายประจำวัน",
    route: "/dashboard",
    targetSelector: '[data-tour="dashboard-overview"]',
    placement: "bottom",
    roles: ["manager"],
    tag: "Executive View",
    icon: "🏠",
    keyHighlight: "📊 ศูนย์รวมดัชนีชี้วัดความคืบหน้าของทีมงานทั้งหมด",
  },
  {
    id: "manager-pipeline",
    stepNumber: 2,
    title: "ภาพรวมการวิเคราะห์ลูกค้า",
    description: "ตรวจสอบการกระจายตัวของลูกค้าในพอร์ตโฟลิโอ สถานะความเร่งด่วน และการเข้าพบของทีมงาน",
    route: "/customers",
    targetSelector: '[data-tour="customer-table"]',
    placement: "top",
    roles: ["manager"],
    tag: "Customer Pipeline",
    icon: "👥",
    keyHighlight: "🔍 ติดตามสุขภาพพอร์ตโฟลิโอและสถานะการตรวจสอบ KYC",
  },
  {
    id: "manager-coverage-gap",
    stepNumber: 3,
    title: "การประเมินความเสี่ยงและช่องว่างความคุ้มครอง",
    description: "วิเคราะห์ช่องว่างความคุ้มครอง (Coverage Gap) ของลูกค้า เพื่อระบุโอกาสทางการตลาดและการบริการเชิงรุก",
    route: "/analytics",
    targetSelector: '[data-tour="analytics-overview"]',
    placement: "bottom",
    roles: ["manager"],
    tag: "Gap Analysis",
    icon: "🛡️",
    keyHighlight: "🎯 ชี้เป้าลูกค้าที่ยังขาดความคุ้มครองหลักเพื่อวางกลยุทธ์ทีม",
  },
  {
    id: "manager-ai-insights",
    stepNumber: 4,
    title: "ระบบ AI Insight & ติดตามประสิทธิภาพทีม",
    description: "ติดตามความแม่นยำของคำแนะนำ AI อัตราการตอบรับข้อเสนอ และแนวโน้มความพึงพอใจของลูกค้า",
    route: "/analytics",
    targetSelector: '[data-tour="analytics-overview"]',
    placement: "top",
    roles: ["manager"],
    tag: "Team Metrics",
    icon: "🧠",
    keyHighlight: "📈 วัดผล Conversion Rate และผลตอบรับของคำแนะนำจาก AI",
  },
  {
    id: "manager-reports",
    stepNumber: 5,
    title: "การกำกับดูแลและรายงานเชิงลึก",
    description: "เข้าถึงรายงานเชิงลึกเพื่อการตัดสินใจเชิงกลยุทธ์ พร้อมรองรับการตรวจสอบมาตรฐานการทำงาน",
    route: "/analytics",
    targetSelector: '[data-tour="analytics-overview"]',
    placement: "bottom",
    roles: ["manager"],
    tag: "Governance",
    icon: "📑",
    keyHighlight: "⚖️ ควบคุมมาตรฐานการให้คำปรึกษาที่โปร่งใสและตรวจสอบได้",
  },
];

export const ADMIN_TOUR_STEPS: TourStep[] = [
  {
    id: "admin-dashboard",
    stepNumber: 1,
    title: "ศูนย์กลางการควบคุมระบบ",
    description: "ภาพรวมสถานะการทำงานของระบบ การเชื่อมต่อ AI Engine และความพร้อมใช้งานของบริการ",
    route: "/dashboard",
    targetSelector: '[data-tour="dashboard-overview"]',
    placement: "bottom",
    roles: ["admin"],
    tag: "System Status",
    icon: "⚡",
    keyHighlight: "🖥️ ควบคุมและตรวจสอบความพร้อมใช้งานของทุก Microservice",
  },
  {
    id: "admin-model-monitoring",
    stepNumber: 2,
    title: "การตรวจสอบความสมบูรณ์ของโมเดล AI",
    description: "ตรวจสอบประสิทธิภาพโมเดล LightGBM Champion, การปรับเทียบ Platt Sigmoid และติดตามการเลื่อนของข้อมูล (PSI Drift)",
    route: "/model",
    targetSelector: '[data-tour="model-metrics"]',
    placement: "bottom",
    roles: ["admin"],
    tag: "Model Health",
    icon: "🔬",
    keyHighlight: "🎯 ตรวจสอบความแม่นยำ F1, ROC-AUC, ECE และการกระจายตัวของข้อมูล",
  },
  {
    id: "admin-shap",
    stepNumber: 3,
    title: "ความโปร่งใสและคำอธิบายโมเดล",
    description: "ตรวจสอบ Feature Attribution ผ่าน SHAP TreeExplainer เพื่อรับประกันความโปร่งใสและไร้อคติในการประเมินผล",
    route: "/model",
    targetSelector: '[data-tour="model-shap"]',
    placement: "top",
    roles: ["admin"],
    tag: "XAI & Ethics",
    icon: "⚖️",
    keyHighlight: "🔍 อธิบายได้ทุกการทำนาย ปราศจากความเสี่ยงทางจริยธรรม AI",
  },
  {
    id: "admin-audit",
    stepNumber: 4,
    title: "บันทึกประวัติการตรวจสอบย้อนกลับ",
    description: "บันทึกทุกคำสั่งการอนุมาน (Inference), คำสั่ง LLM และการตัดสินใจของผู้ใช้ เพื่อการกำกับดูแลตามข้อกำหนด",
    route: "/admin/audit",
    targetSelector: '[data-tour="audit-log-table"]',
    placement: "top",
    roles: ["admin"],
    tag: "Compliance Log",
    icon: "📜",
    keyHighlight: "🔒 บันทึกข้อมูลที่แก้ไขไม่ได้ (Immutable Audit Trail) 100%",
  },
  {
    id: "admin-pilot",
    stepNumber: 5,
    title: "การทดสอบนำร่องและการจำลองสถานการณ์",
    description: "จำลองสถานการณ์ทดสอบ 8 รูปแบบเพื่อประเมินความพร้อมและเสถียรภาพของระบบก่อนการปรับใช้จริง",
    route: "/pilot",
    targetSelector: '[data-tour="pilot-sandbox"]',
    placement: "bottom",
    roles: ["admin"],
    tag: "Pilot Sandbox",
    icon: "🧪",
    keyHighlight: "🚦 เครื่องมือวัดผลและทดสอบความพร้อมในสภาพแวดล้อม Sandbox",
  },
];

export const FEATURE_CATALOG_ITEMS: FeatureCatalogItem[] = [
  {
    id: "feat-dashboard",
    title: "1. แดชบอร์ด & คิวงานด่วน AI",
    subtitle: "ภาพรวมลูกค้าด่วนประจำวัน งานติดตาม และคำแนะนำกลยุทธ์ AI",
    icon: "🏠",
    route: "/dashboard",
    stepIndex: 0,
    tag: "Daily Cockpit",
    highlights: ["ลูกค้าความสำคัญสูงประจำวัน", "งานติดตามพร้อม Checkbox", "สรุปกลยุทธ์ AI ประจำเช้า"],
  },
  {
    id: "feat-customers",
    title: "2. ฐานข้อมูลลูกค้า & ค้นหาอัจฉริยะ",
    subtitle: "ค้นหาและคัดกรองลูกค้าตาม Priority และสถานะ KYC",
    icon: "👥",
    route: "/customers",
    stepIndex: 1,
    tag: "Customer Directory",
    highlights: ["ค้นหาด่วนด้วยชื่อหรือรหัสลูกค้า", "กรองตามระดับความเร่งด่วน", "จัดการรายชื่อลูกค้าแบบเรียลไทม์"],
  },
  {
    id: "feat-customer-360",
    title: "3. ข้อมูลลูกค้า 360° & Gap ความคุ้มครอง",
    subtitle: "ข้อมูลส่วนตัว สินทรัพย์ ภาระหนี้ และวงล้อประเมิน 5 มิติ",
    icon: "👤",
    route: "/customers/KS-00001",
    stepIndex: 2,
    tag: "Customer 360°",
    highlights: ["วิเคราะห์ความคุ้มครองครบ 5 มิติ", "รวมประวัติกรมธรรม์เดิมในหน้าเดียว", "ชี้เป้าความเสี่ยงที่ยังขาด"],
  },
  {
    id: "feat-ai-insight",
    title: "4. AI Why Now & ปัจจัย TreeSHAP",
    subtitle: "อธิบายเหตุผลว่าทำไมต้องติดต่อ ด้วยปัจจัยบวก/ลบภาษาไทย",
    icon: "🧠",
    route: "/customers/KS-00001",
    stepIndex: 3,
    tag: "TreeSHAP Explainability",
    highlights: ["อธิบายเหตุผลคะแนนความเร่งด่วน", "แจกแจงปัจจัยบวก/ลบภาษาไทย", "โปร่งใส ไร้โมเดลกล่องดำ"],
  },
  {
    id: "feat-recommendations",
    title: "5. คำแนะนำผลิตภัณฑ์คัดกรอง 100%",
    subtitle: "Hard Eligibility Gate กรองเงื่อนไขตายตัว 0% ข้อเสนอผิดเกณฑ์",
    icon: "🛡️",
    route: "/customers/KS-00001",
    stepIndex: 4,
    tag: "Hard Eligibility Gate",
    highlights: ["กรองคุณสมบัติ 100% ป้องกันเสนอผิด", "จับคู่ผลิตภัณฑ์ตาม Gap ลูกค้า", "นายหน้ากดตัดสินใจเอง"],
  },
  {
    id: "feat-nearby",
    title: "6. แผนที่ลูกค้าใกล้เคียงตามรัศมี",
    subtitle: "Proximity Radar ค้นหาลูกค้ารอบตัว 5/10/20 กม.",
    icon: "📍",
    route: "/visit-planner",
    stepIndex: 5,
    tag: "Proximity Map",
    highlights: ["แผนที่เรดาร์พิกัดลูกค้าและสำนักงาน", "กรองรัศมี 5, 10, 20 กม.", "เห็นระยะทางและคะแนนความเร่งด่วน"],
  },
  {
    id: "feat-selection",
    title: "7. คุณเป็นคนเลือก (Human Autonomy)",
    subtitle: "นายหน้าเป็นผู้ตัดสินใจเลือกเองว่าจะไปพบลูกค้ารายใด",
    icon: "✋",
    route: "/visit-planner",
    stepIndex: 6,
    tag: "Broker Autonomy",
    highlights: ["AI สนับสนุนแต่นายหน้าตัดสินใจเอง", "อิสระในการเลือกพบลูกค้า 100%", "ไม่บังคับตารางเวลา"],
  },
  {
    id: "feat-navigation",
    title: "8. ระบบนำทางจริง Google Maps",
    subtitle: "ปุ่มเปิด Google Maps นำทางจริงแบบจุดต่อจุด On-Demand",
    icon: "🧭",
    route: "/visit-planner",
    stepIndex: 7,
    tag: "On-Demand Navigation",
    highlights: ["เปิด Google Maps นำทางจริงใน 1 คลิก", "จัดเส้นทางวนรอบ Loop ประหยัดเวลา", "รองรับ GPS บนอุปกรณ์พกพา"],
  },
  {
    id: "feat-analytics",
    title: "9. ศูนย์วิเคราะห์ข้อมูลผลงานและธุรกิจ",
    subtitle: "Coverage Gap, Conversion Rate, และส่งออกรายงาน CSV",
    icon: "📊",
    route: "/analytics",
    stepIndex: 8,
    tag: "Business Analytics",
    highlights: ["วิเคราะห์ความคืบหน้าพอร์ตโฟลิโอ", "สถิติการตอบรับคำแนะนำผลิตภัณฑ์", "ส่งออกรายงาน Excel/CSV ภาษาไทย"],
  },
];

export function getTourStepsForRole(role?: string): TourStep[] {
  switch (role) {
    case "admin":
      return ADMIN_TOUR_STEPS;
    case "manager":
      return MANAGER_TOUR_STEPS;
    case "broker":
    default:
      return BROKER_TOUR_STEPS;
  }
}
